### ISSUE TITLE
Refactor/Rename function name wrongly refuse colon

### ISSUE THREAD

**Issue by leagris** [BashSupport-Pro/bashsupport-pro#101]
#### Description
In BashSupportPro 2.1.4.213 `Refactor/Rename…` a function containing colon characters `:` is wrongly denied.

#### What happens
This wrong limitation prevents the `Refactor/Rename…` feature to be used to rename function names with a colon character.

#### What is expected
When building Bash-shell library files to be sourced, it is a common and valid practice to prefix function names 
with the library name.

Namespacing like `library_name::function_name` prevents shadowing main Bash-script functions with name collisions.
Colons are **perfectly legal for function names**.
\(*They are only **illegal for variable names***.)

BashSupport Pro should not refuse to `Refactor/Rename…` function names containing colons.

#### Reproducing

Create a function:

```sh
function_name () { :;}
```
Place cursor over  `function_name` and select `Refactor/Rename…` for example with:
<kbd>shift</kbd>+<kbd>F6</kbd>
and enter `lib_name::func_name` as the new name.

Here is how it wrongly refuses the rename:

![image](https://user-images.githubusercontent.com/1111474/154363627-8c994b11-174d-4e6d-b39a-cb2ed4507916.png)

**Comment by jansorg** [comment]
@leagris Thank you for your feedback!
This has already been fixed for the 3.0 beta releases, https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/eap-bashsupport-pro-3-0/changes

I've backported this change for the next update of 2.1. If you need this now or would like to make sure that it's what you need, please consider to use the already available [beta version](https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/eap-bashsupport-pro-3-0/).

**Comment by leagris** [comment]
Thank-you, tested 3.0.0.213-beta4-eap and it now works as expected.

**Comment by jansorg** [comment]
Thanks for confirming! 2.0.5 with the backport is now also available.
