### ISSUE TITLE
Using IntellijJ IDEA CE, is there a way to use / reference externally sourced functions

### ISSUE THREAD

**Issue by vagharsh** [BashSupport-Pro/bashsupport-pro#105]
i am using IntelliJ IDEA CE, and i have couple of projects working which are sourcing some other shell scripts which are being added in the Dockerfile so while debugging some functions i want to click on the function and see what the function is doing.

is there a way to source external libraries ?
is this something on your end or IntelliJ IDEA related functionality ?

thanks.

**Comment by jansorg** [comment]
Hi @vagharsh , there's a page in the manual explaining how to source files: https://www.bashsupport.com/manual/navigation/sourced-files/

Ctrl+Click on a function is possible if the sourced script has been properly located. 
Could you elaborate a bit how you're using this in Docker? Sourcing files from within a Dockerfile won't work out-of-the-box, but with a bit of context I might be able to help.

IntelliJ IDEA's shell plugin and BashSupport Pro are separate pieces of software, so it's all provided by BashSupport Pro.

**Comment by vagharsh** [comment]
before building my application dockerfile i am copying some libraries from other locations and performing ADD into the dockerfile.

i am doing cmd+click on the function but the plugin is not able to find the function declaration because the function is not located in the application repo and it's going to be available after the docker image build. so the scripts work.

1 - copy files from different location to where the dockerfile is located
2 - build docker image
3 - run application, application is sourcing the functions correctly

i need a way to provide in the bashsupportpro plugin configuration a path where all my functions are stored.
is there a way to achieve it ?

**Comment by jansorg** [comment]
Yes, that's possible as far as I understand the requirements.
There's a feature called "libraries", explained at  https://www.bashsupport.com/manual/navigation/libraries/ .

You need to setup a new library:
1. Library Name: Your own choice
2. Library sources: Most likely the directory containing the files you copy at (1) of your description. These are the files used by the script where you cmd+click.
3. Library Usage: The shell script file where you cmd+click. Or the directory, if there's more than one file.

Are you cmd+clicking inside the Dockerfile or in a script executed by the Dockerfile?
Cmd+Click on `RUN:` snippets inside of a Dockerfile won't work, as far as I know. I've never considered that yet as a use-case. If you need that, I could check if it's possible to support.

**Comment by vagharsh** [comment]
it worked, thanks .. but how can we have have this on all projects .. and not assign one by one ? i have over 30 projects i am working on ;)

**Comment by jansorg** [comment]
Hm, that's a tough one :) The libraries are project-level settings. Application-level library settings are not supported, so far.

Would all library definitions refer to the same "source" and "usage" files? If that's the case, then it should be possible to copy the file `.idea/bashsupport-pro.xml` into the `.idea` of your projects. If the projects live in different parent folders, you should change the relative paths in the `.xml` file into absolute paths before you copy it.

This is untested, but should work :) If there's a problem with it, please let me know!
