### ISSUE TITLE
<edited>

### ISSUE THREAD

**Issue by iamtowne** [BashSupport-Pro/bashsupport-pro#107]
I just want to execute a shell, and you want me dollars！

**Comment by jansorg** [comment]
Please use https://www.jetbrains.com/help/idea/shell-scripts.html in this case, which comes bundled with all JetBrains IDEs. 
I'm not sure why you installed BashSupport Pro, let me know if there something I can do about it.

**Comment by iamtowne** [comment]
I just upgraded the idea but he told me I couldn‘t execute *.sh and told me to pay . Maybe I will pay for it, but obviously I don't want it right now, do I just want to run shell in my idea and that's all

**Comment by jansorg** [comment]
I'm not sure why the plugin was installed for you. 
Just uninstall "BashSupport Pro" and make sure that "Shell Script" is enabled at "Preferences > Plugins > Installed". The JetBrains Shell Script plugin allows you to execute scripts.

**Comment by iamtowne** [comment]
My version . PyCharm 2021.3.2 (Community Edition), After I uninstall "BashSupport Pro" and that "Shell Script" is enabled. how to execute scripts. 
![image](https://user-images.githubusercontent.com/3862689/163983070-ac7cd3fd-00db-4130-908d-463b8f87211f.png)

**Comment by jansorg** [comment]
Make sure to assign your shell script files to the plugin at `Preferences > Editor > File Types > Shell script`. For example, add `*.sh` and `*.bash` in the "File name patterns" table. AFAIK it's a bug that the IDE does not restore the file types after a plugin uninstallation, but I'm not sure.

**Comment by iamtowne** [comment]
Thanks for your patient response, sorry for the offend

**Comment by iamtowne** [comment]
it ok!
