### ISSUE TITLE
我英文不好，所以用中文提交一个小问题。

### ISSUE THREAD

**Issue by super-vip** [BashSupport-Pro/bashsupport-pro#110]
首先定义一个变量: diskTotalSize
diskTotalSize="$(lsblk -b 2>>"${scriptLogFile}" | grep disk | awk '{total+=$4/1024/1024/1024}END{print total}')"

然后打印这个变量: ${diskTotalSize}
echo ${diskTotalSize:=0}

此时，将有如下提示：
![image](https://user-images.githubusercontent.com/19517568/170388576-ef0d1fca-1df5-4bfd-acb0-787f254a6342.png)

虽然不影响功能和使用，但是这个提示信息依旧让人感觉奇怪……

**Comment by jansorg** [comment]
Unfortunately, I don't understand what the problem is. If this is related to BashSupport Pro, could you perhaps explain what you're seeing and what you expected from BashSupport Pro! Thanks!
