### ISSUE TITLE
Please get rid of `com.intellij.openapi.util.SystemInfoRt#is64Bit` usages in the code

### ISSUE THREAD

**Issue by trespasserw** [BashSupport-Pro/bashsupport-pro#111]
`com.intellij.util.system.CpuArch` is more detailed.

**Comment by jansorg** [comment]
Thanks! The next major version (3.0) has already remove usage of `SystemInfoRt#is64Bit`. Is that soon enough or is it important to remove usage before 2022.2 is out?

**Comment by trespasserw** [comment]
The next version is enough, no need to hurry. Thanks!
