### ISSUE TITLE
New BashSupport Pro files being automatically add to version control (Git)

### ISSUE THREAD

**Issue by wobondar** [BashSupport-Pro/bashsupport-pro#112]
Hi Team,

Being use an amazing plugin BashSupport Pro for a long time I've constantly experienced issues when trying to create a new Bash Support Pro file that automatically adds it to Version Control, although, this is clearly set and configured under Preferences -> Version Control -> Confirmation -> When files are created: **Do not add**.

That strange behavior I can reproduce only with the BashSupport Pro plugin.

<details><summary>Expected behavior with a normal file or any other new files: (click to view)</summary>

#### create new file and chose 'File'
<img width="800" alt="create_new_file" src="https://user-images.githubusercontent.com/6381768/186388157-65244e51-80e3-417e-9f1d-cd3cf890571c.png">

#### name it `test_file.sh`

<img width="800" alt="bashpro_step2" src="https://user-images.githubusercontent.com/6381768/186388933-275d5da1-f3a2-4aa5-a4ee-6de33be3f0f2.png">

#### file has been created without adding it to Version Control (red colored)

<img width="800" alt="file_created_1" src="https://user-images.githubusercontent.com/6381768/186389665-39d40ee0-5f09-4e88-b57e-0b0a331fe10c.png">

</details>

#### create new file and choose 'Shell Script'

<img width="800" alt="new_bash_pro_file" src="https://user-images.githubusercontent.com/6381768/186390411-c5b61db5-2fe6-4289-bb71-9a8db68d723c.png">

#### name it `test_file_2.sh`

<img width="800" alt="bashpro_step5" src="https://user-images.githubusercontent.com/6381768/186391061-bd3c5018-1859-44d1-add4-5d62a3883909.png">

#### file has been created automatically adds it to Version Control (green colored)

<img width="800" alt="file_created_2" src="https://user-images.githubusercontent.com/6381768/186391576-751b0787-f7b5-4e42-8574-a82b52c81bb2.png">

### Preferences -> Version Control -> Confirmation

<img width="800" alt="bashpro_step7" src="https://user-images.githubusercontent.com/6381768/186392031-5824fe22-3c66-4b05-9c7c-ad9f1c8c0daa.png">

BashSupport Pro 2.1.9.222
GoLand 2022.2.1, and other JetBrains IDE's WebStorm, IntelliJ IDEA tested.

Thank you, you're doing a great job!

<details><summary>IDE, OS, and plugin versions</summary>
<p>

```
GoLand 2022.2.1
Build #GO-222.3345.146, built on August 4, 2022
Runtime version: 17.0.3+7-b469.32 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Metal Rendering is ON
Registry:
    suggest.all.run.configurations.from.context=true
    ide.completion.variant.limit=500

Non-Bundled Plugins:
    org.intellij.plugins.hcl (222.3345.108)
    com.github.lppedd.idea-conventional-commit (0.21.0)
    izhangzhihao.rainbow.brackets (6.25)
    com.codestream.jetbrains-codestream (13.5.0+247)
    ru.adelf.idea.dotenv (2022.2)
    pro.bashsupport (2.1.9.222)
    aws.toolkit (1.49-222)

```
</p>
</details>

**Comment by jansorg** [comment]
Thank you for your detailed report! I was able to reproduce this and will fix it for the next 2.x update.
I'm always glad for user feedback, please feel free to report whatever is irritating with the plugin!

**Comment by jansorg** [comment]
Fixed for 2.1.10, which will be out later this week. An additional rename of the new file was causing it to be added to VCS.
Thanks!

**Comment by wobondar** [comment]
@jansorg thanks a lot! I'll close this issue once it fixed.

**Comment by jansorg** [comment]
@wobondar 2.1.10 is available now. I'd be glad if you tested it. Thanks!

**Comment by wobondar** [comment]
@jansorg can confirm that has been fixed.
I've tested each option `Do not add`, `Ask` `Add silently`.

Many thanks!
