### ISSUE TITLE
Some highlighted rendering issue?

### ISSUE THREAD

**Issue by mylovesaber** [BashSupport-Pro/bashsupport-pro#119]
If a variable inside a function is set as a local variable, the variable will lose its highlighting effect.

code:
```shell
#!/bin/bash
aaa(){
#    local aaa
    aaa=1
    echo $aaa
}
```

![image](https://user-images.githubusercontent.com/36480362/202852900-087df336-86b7-4ad4-a79a-93698b2cf9ef.png)
↑comment
↓uncomment
![image](https://user-images.githubusercontent.com/36480362/202852917-3f5d29a2-9da5-4052-9ef0-e52668256c3d.png)
![image](https://user-images.githubusercontent.com/36480362/202853135-e2505096-b1af-40b2-8dc3-51cb66098692.png)

**Comment by mylovesaber** [comment]
Another example:
![image](https://user-images.githubusercontent.com/36480362/202911177-83293fe5-cae7-48ee-b6d8-6903d925bea1.png)
reference link: https://github.com/koalaman/shellcheck/wiki/SC2004

**Comment by jansorg** [comment]
Thanks!
Are you using a customized theme or which theme is installed?

3.0.3 fixed a few issues of highlighting local variables. `local aaa` in your first example is controlled by `Variables > Bash > Local Variable Declaration` and `aaa=1` by `Variables > Bash > Reassigned local variable`. Is this what you need?

The missing highlighting in your 2nd example seems like a bug. I'll fix it for the next update.

![image](https://user-images.githubusercontent.com/11473063/203025240-16f88173-4cd9-4c99-8316-41d267718d05.png)

**Comment by mylovesaber** [comment]
https://github.com/BashSupport-Pro/bashsupport-pro/issues/119#issuecomment-1321819856

Theme name: One Dark
For aaa example.
I'm not sure if my understanding of highlighting is wrong.

What I understand is that if you only add a global variable in the function, then the variable name should be red according to the theme color.

If you change this global variable into a local variable, that is, add "local aaa" on the line above "aaa=1", then "aaa" after "local" and "aaa of aaa=1" should be red at the same time. Not the color becomes white.

**Comment by jansorg** [comment]
There are different highlighting settings for global and local variables. Local variables are currently highlighted as "white" by default. But I agree that this is a bit confusing, I'll look into this again.
JetBrains' plugins, e.g. the Java support, merge the highlighting settings of "global variable" and "local variable" for local variables. Perhaps that's the way to fix it, even though it's odd.

**Comment by jansorg** [comment]
The One Dark theme is intentionally highlighting local variables as white. You can change this at `Preferences > Editor > Color Scheme > Language Defaults > Identifiers > Local variable" and similarly for `... > Identifiers > Reassigned local variable`.

I'll fix the highlighting of "Reassigned local variable" for the next update, but the white color is as the One Dark theme defined it.

**Comment by jansorg** [comment]
3.0.4 (released yesterday) fixed the highlighting of "Reassigned local variable". As far as I understand, the remaining issue is part of the One Dark theme.
