### ISSUE TITLE
IDE Internal Errors

### ISSUE THREAD

**Issue by mylovesaber** [BashSupport-Pro/bashsupport-pro#121]
![image](https://user-images.githubusercontent.com/36480362/204096443-8156c0d1-467b-40d2-b05c-387d3e43bef7.png)

What does this mean?

**Comment by jansorg** [comment]
Seems like a bug. I'll debug this for the next update.
Do you remember what you did when this popped up?

Please report such issues with the "Report and Clear All", then they'll show up in BashSupport Pro's exception tracking system.

**Comment by mylovesaber** [comment]
I push a commit to remote dev branch. As you can see, this commit just move a folder with many subfolders to another folder and delete a file.
https://gitlab.com/mylovesaber/tools-share/-/commit/ef2d7cf5ed976e10ea85e51173366916d6b8ebc1

I forgot to choose this option...

**Comment by jansorg** [comment]
I've fixed this for the next update...

**Comment by jansorg** [comment]
This should hopefully be fixed by 3.0.4, which was released yesterday.
