### ISSUE TITLE
Virus report for shfmt_windows_amd64.exe

### ISSUE THREAD

**Issue by rquadling** [BashSupport-Pro/bashsupport-pro#122]
Running Avast on MacOS.

![image](https://user-images.githubusercontent.com/12801/205112377-4fb22a67-fcb1-4386-acc2-75c47b89323f.png)

False positive though? : https://www.virustotal.com/gui/file-analysis/YWI2ZjkxN2IyMGE5NzY5NTRhNmM2YjY2MDIyNjRlYTI6MTY2OTkxMzc4OQ==

**Comment by jansorg** [comment]
Thanks for the report!

This is a false positive, I'm building and signing all bundled binaries myself and don't rely on 3rd-party binaries. shfmt is a Golang program and Golang-compiled programs tend to be detected as false-positives. The exe file's code signature seems to be [still valid](https://www.virustotal.com/gui/file/d10d064927ced01c14f9954bcc8958ceed2a4491f0f4bddcec5aa2be04450933/details) on VirusTotal.

You're on macOS, so you could just leave the exe file in quarantine.
I'll try to report this as a false positive to Avast, but that will take a few days to process, I think.

Even the official shfmt 3.4.1 and the current 3.5.1 binaries are detected incorrectly.
3.4.1: https://www.virustotal.com/gui/file/0d0cb61d85192725eb6140457ea29a3ba07d07ef339f638c9f095045aad44136/detection
3.5.1: https://www.virustotal.com/gui/file/f759493bc55a4ea181442eb7d79b527ff6c15d62ec567b8b86a5df6a086c9c46

BashSupport Pro's shfmt binaries use a slightly different source code and compilation command and are also code signed, so results are different.

**Comment by rquadling** [comment]
All as expected. Thanks for the response.
