### ISSUE TITLE
Unassigned local variable notice when passing as a reference

### ISSUE THREAD

**Issue by john-f-chamberlain** [BashSupport-Pro/bashsupport-pro#124]
Example code:
```bash
function array_function() {
  local arg1=$1
  local -n array_reference=$2

  # ... do something with array
}

function main() {
  local local_array=(
    "Element 1"
    "Element 2"
    "Element 3"
  )
  array_function "Argument 1" local_array
}

main "$@"

```

This code causes BashSupport Pro to put the notice "unused local variable" on "local_array"

I understand that BashSupport likely cannot understand that this variable is being passed as a reference, but it would be nice if there was a comment such as `# bashsupport uses=local_array` that could be placed above `array_function "Argument 1" local_array` to disable this warning about an unused variable.

**Comment by jansorg** [comment]
Thanks for reporting!

The only workaround for now is to place "# bashsupport disable=BP3001" above "local local_array=..." or above the function declaration of "main". Would this be sufficient for your use-case or do you need it on the line where it's referenced?

I noticed that the UI to insert this comment is confusing, it should have been "Alt + Enter > Disable for statement" as usual. I'll improve the UI/UX for this particular case.

**Comment by john-f-chamberlain** [comment]
That's perfect! I just want it to not yell at me for a variable I know is in use, but I also don't want to disable the notice entirely as it's generally very helpful, so this solution works for me.

**Comment by jansorg** [comment]
The next major version will have improved support for this.
The confusing "Prefer BashSupport Pro" quickfix on the unused variable won't be shown and it will also be possible to suppress the warning with `# shellcheck disable=SC2034`, which is used by ShellCheck for both global and local variables. For 3.x you'll have to use the comment discussed above.
