### ISSUE TITLE
bats_load_library Fails To Run

### ISSUE THREAD

**Issue by JohnMSRed** [BashSupport-Pro/bashsupport-pro#125]
I'm running PyCharm 2022.3.1 with BashSupport-Pro 3.1.0.223. When I click the run all tests button I get the following error:

> C:\cygwin64\bin\bash.exe /cygdrive/c/Users/USER-NAME/AppData/Roaming/JetBrains/PyCharmCE2022.3/plugins/bashsupport-pro/bats-core/bin/bats -F bashpro -r /cygdrive/d/sources/REPO/PROG1/TESTSA.bats
> Testing started at 9:53 ...
> 1..20
>   ---
> # (in test file TESTSA.bats, line 6)
> #   `bats_load_library "bats-assert"' failed with status 0
> # Could not find library 'bats-assert' relative to test file or in BATS_LIB_PATH
> # bats warning: Executed 1 instead of expected 20 tests

Is there something that I was suppose to set-up to run unit tests?

**Comment by jansorg** [comment]
Thanks for reporting!
This is supposed to run out of the box, because `bats-assert` is bundled with the plugin.
There may be a problem with the setup of the environment variables. A bats-core environment variable is used to tell it about the path where `bats-assert` is located.

Could you post a screenshot of your tests's run configuration, please?

**Comment by JohnMSRed** [comment]
Here ya go:
![Debug Configuration](https://user-images.githubusercontent.com/122602058/212287576-a2b0a53a-9d54-492b-8aca-2ebfa2f9d86a.png)

The environment variable section contains:
Path=C:\Program Files\Python39\;C:\Program Files\Python39\Scripts\;C:\Windows\system32\;C:\Windows\;C:\Windows\System32\Wbem\;C:\Windows\System32\WindowsPowerShell\v1.0\\;C:\Windows\System32\OpenSSH\\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR\;C:\Users\USER_NAME\AppData\Local\Microsoft\WindowsApps\;

All other sections are empty.

**Comment by jansorg** [comment]
I can confirm that this is a bug. Unfortunately, there's no good workaround.
I've fixed this for the next update, which will be out soon. I've tested the fix with Cygwin, Git Bash and WSL on Windows 10.
Thanks for reporting, that's really appreciated!

**Comment by jansorg** [comment]
@JohnMSRed Version 3.1.1 has just been released and should fix the bug. Please let me know if that's not the case. Thanks!

**Comment by JohnMSRed** [comment]
Works great here. Thanks.
