### ISSUE TITLE
Bats Assert Errors Out When a Test Fails

### ISSUE THREAD

**Issue by JohnMSRed** [BashSupport-Pro/bashsupport-pro#128]
When the assert command activates due to a failed condition instead of writing out the error message and ending the test, it fails completely. I'm using Cygwin but I've also reproduced it on Fedora as well.

Demonstration of the error:
```
#!/usr/bin/env bats
shopt -s -o nounset
shopt -s -o errexit
shopt -s extglob

bats_load_library "bats-assert"

@test "demo of error" {
	run echo "This should fail."
	assert_output "This totally failed."
}

```

Output from test execution:

```
> C:\cygwin64\bin\bash.exe /cygdrive/c/Users/USERNAME/AppData/Roaming/JetBrains/PyCharmCE2022.3/plugins/bashsupport-pro/bats-core/bin/bats -F bashpro -f ^demo[[:space:]]+of[[:space:]]+error$ -r /cygdrive/d/sources/unit-tests/Example.bats
> Testing started at 9:21 ...
> 1..1
>   ---
> # (from function `assert_output' in file /cygdrive/c/Users/USERNAME/AppData/Roaming/JetBrains/PyCharmCE2022.3/plugins/bashsupport-pro/bats-core-libs/bats-assert/src/assert_output.bash, line 194,
> #  in test file Example.bats, line 10)
> #   `assert_output "This totally failed."' failed with status 127
> # /cygdrive/c/Users/USERNAME/AppData/Roaming/JetBrains/PyCharmCE2022.3/plugins/bashsupport-pro/bats-core-libs/bats-assert/src/assert_output.bash: line 190: batslib_print_kv_single_or_multi: command not found
> # /cygdrive/c/Users/USERNAME/AppData/Roaming/JetBrains/PyCharmCE2022.3/plugins/bashsupport-pro/bats-core-libs/bats-assert/src/assert_output.bash: line 193: batslib_decorate: command not found
> # /cygdrive/c/Users/USERNAME/AppData/Roaming/JetBrains/PyCharmCE2022.3/plugins/bashsupport-pro/bats-core-libs/bats-assert/src/assert_output.bash: line 194: fail: command not found
>   ...
> 
> demo of error
> 
```

**Comment by jansorg** [comment]
@JohnMSRed Apologies for the late reply.
What would you expect as output?

As far as I can tell, you're missing a `bats_load_library "bats-support"` to load the helper functions used by `bats-assert` (see the messages about `command not found` in your output).

**Comment by JohnMSRed** [comment]
I see. I understood that `bats_load_library "bats-assert"` would load all the libraries it needs to work, i.e. `bats_load_library "bats-support"`.

**Comment by jansorg** [comment]
I‘m not entirely sure, it‘s part of the bats-core libraries. I‘ll double-check that the bundled btw-core libraries are not missing anything

**Comment by jansorg** [comment]
If I'm not mistaken, the bats-assert library is [manually loading its dependencies](https://github.com/bats-core/bats-assert/blob/42e4d8622eda821d8c7c1a9fdcdbef54c642cf59/test/test_helper.bash#L3) for tests and a bats-core tutorial is [doing the same](https://bats-core.readthedocs.io/en/stable/tutorial.html#dealing-with-output).  But IMHO it's rather unclear and not well documented.
I'm closing this because it's a required step to load dependencies first. Please reopen if you don't agree.
