### ISSUE TITLE
History in BashSupport Pro does not work

### ISSUE THREAD

**Issue by Jack31071973** [BashSupport-Pro/bashsupport-pro#132]
I am a happy user of BashSupport Pro, anyway the history on it does not work. I saved something but never the last things.

**Comment by jansorg** [comment]
Could you post a screenshot of it, please? 
I’m not sure which one of the histories you meant. Thanks!

**Comment by Jack31071973** [comment]
Sorry my bad, It is my problem.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jansorg** [comment]
Thank you for your follow-up!
