### ISSUE TITLE
File and folder navigation

### ISSUE THREAD

**Issue by NickSdot** [BashSupport-Pro/bashsupport-pro#134]
Hi there! 

I am using BashSupportPro for over a year now and appreciate it a lot. Thanks! One thing is bugging me. Not sure if this is a missing feature, a bug or I am simply missing something. 

## Actual

Navigation to a file or folder by clicking on the path element works.

```sh
source "../scripts/core.config.sh"
```

Navigation does not work at all with custom functions

```sh
someFunctionA "../scripts/core.config.sh"
```

```sh
someFunctionA \
  "../scripts/core.config.sh" \
  "../scripts/helpers/utils.sh" \
  "../../libs/foo/HasAll.sh"
```

Special case. Navigation to a file works only in the very first line (this is a over ridden source function with a loop).

```sh
source \
  "../scripts/core.config.sh" \      #  <--- this works
  "../scripts/helpers/utils.sh" \
  "../../libs/foo/HasAll.sh"
```

## Expected

It would be cool if navigation would work for any path (passed to vars and functions) and not only when used with a `source` function. 

## Environment
Latest MacOS, latest IntelliJ, latest BashSupportPro

---

Is there a way I am not aware of? It is worth noting that the behavior described applies to both, relative and absolute paths. 

Thanks in advance. 🙏

**Comment by jansorg** [comment]
@NickSdot Thanks for your feedback!

There's currently no generic support for file paths. There's special support for the 1st argument passed to `source` (and `.`), because behavior is known and defined by Bash. `source` is matched by name to avoid a performance penalty while highlighting a Bash file.

There's currently no generic support because it's no always the case the file paths (and especially relative file paths) should link to project files. An argument passed to a Bash function `someFunctionA` may or may not be used as a file path.
Renaming and moving the resolved target of such path would update the value, e.g. `"../scripts/core.config.sh"` would become `"../scripts_renamed/core.config.sh"` if you renamed directory `scripts`. 

Would you just like code completion for such paths or also the update on rename/move and support for ctrl+click (i.e. "Go to declaration")?

There may be a way to handle paths passed to functions less "agressively", but I'd first like to know what you'd like as a user.

**Comment by NickSdot** [comment]
Thanks for your answer, @jansorg.

> Would you just like code completion for such paths or also the update on rename/move and support for ctrl+click (i.e. "Go to declaration")?

Personally, I would prefer to have the full functionality – which includes refactoring, too. Since I just realised the complexity, completion alone would be a good first quick win.

> There's currently no generic support because it's no always the case the file paths (and especially relative file paths) should link to project files. An argument passed to a Bash function someFunctionA may or may not be used as a file path.

I see where you are coming from here. While I – solely based on my personal experience – would argue that it is a rare case that a path _which has a "match"_ in the project scope is not meant to target that matched file/folder, it surely can not be ruled out completely. That's indeed an interesting problem, which likely does not have a 'one fits all' solution and, hence, might better a be an opt-in/out feature. Thinking this further, in some cases one might want to opt out for specific functions.

Not sure how much effort, if any, you would like to put into this topic. But here is two ideas I can come up with:

1) Setting on/off to globally opt in/out to this behaviour, plus directives to opt in/out specific functions.
2) Allow in settings to define functions that opt in; similar approach as with the project vars.

Personally, I would prefer approach 1.

Thanks again, Joachim.

**Comment by jansorg** [comment]
@NickSdot I added generic path handling for the next major version (4.0). The release is still far away, but I hope to provide preview releases as soon as it stabilized.
For now it's not controlled by a setting and always available, e.g. for `myFunction path/file.sh` and `echo path/file.sh`. If it turns out that this is too much, then I'll add a global setting to control it application-wide.

**Comment by NickSdot** [comment]
Thank you @jansorg, you are amazing! Can't wait to get my hands on it. Feel free to ping me when the preview is available. Keen to test and provide feedback.

**Comment by jansorg** [comment]
@NickSdot I published 4.0 beta1, which contains the changes for the extended path handling. It ended up as a rewrite of most of the file reference handling, but it should be much better now.

I'd be glad for your testing and your feedback.
Please note that it's an very early preview, things like Zsh support still very immature.
Everything in 3.0 and also the new path handling should be stable, though.

**Comment by jansorg** [comment]
You can find more information at https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/versions/eap/328772, a manual install is easiest for now.

**Comment by NickSdot** [comment]
Nice, the release turned out to be not that far away. 😅 Thanks @jansorg!

Already read the release notes. Can't wait to get my hands on it and will do so right tomorrow morning.

Feedback follows. 👌

**Comment by jansorg** [comment]
Thanks! The final 4.0 release will most likely  take a long time because supporting Zsh is difficult. But everything else in the beta releases should be fine, already.

**Comment by NickSdot** [comment]
Hi @jansorg, thanks for pinging me!

As promised I got my hands on the EAP version today morning. Solely focusing on the paths feature for now. Yet in the short time I tried I could not find any issues. Tested on latest MacOs / M1, latest IntelliJ, BashSupportPro EAP.

1. Paths are navigable, no matter they are in one line, in multiple lines, or multiple in one line. It also works from like everywhere, no matter the file editor itself or the editor in the 'Find in Files' modal.
2. Renaming and it's reverting works.
3. Moving and it's reverting works

Works like a charm. Happy with it!

# Edge Cases

## Vars
The functionality to have the same behaviour for vars seems not implemented?

```bash
foo="../bootstrap/executables.sh"
```
Did you in general decide against it?

## Non-constant paths. 

Points given that the following are having a var prepended and that this is the same as with `source "$HOME/something.sh"`. I would like to mention it anyway.

```bash
builtin source "${md_executable_directory_path}/../bootstrap/executables.sh"
```
What I do in the above example is to prepend the current files directory to the path. Also tried to remove the leading slash. Doesn't change the behaviour:

```bash
builtin source "${md_executable_directory_path}../bootstrap/executables.sh"
```

While this works:
```bash
builtin source "../bootstrap/executables.sh"
```

Same without temp var.
```bash
builtin source "$(dirname "${BASH_SOURCE:-$([ "$ZSH_VERSION" ] && eval echo '${(%):-%x}')}")/../../libs/pot/Core.sh"
```

The only benefit I see in these also working, is that I would be able to easily confirm that my path is correct by hovering it. Could live without it in this special case, though. Still, since these are paths that are relative to the current file and hence theoretically could be clickable, I report it for completeness.

If this would work:
```bash
foo="../bootstrap/executables.sh"
```

I could work around it with:
```bash
foo="../bootstrap/executables.sh"
builtin source "${md_executable_directory_path}/${foo}"
```

You likely have valid reasons to not do that. Alternatively, I could imagine a special directive for opt-in. 
```bash
# bashsupport relative
foo="../bootstrap/executables.sh"

# bashsupport relative
builtin source "${md_executable_directory_path}../bootstrap/executables.sh"

# bashsupport relative
source "$HOME/something.sh"
```

But I don't want to ask for too much, though. The new feature is already a game changer. Thanks for that!

Reopened for visibility. If you decide that these are not worth to look at - which I would understand, feel free to close again.

**Comment by jansorg** [comment]
@NickSdot 
> The functionality to have the same behaviour for vars seems not implemented?

I simply missed this case. Plain assignments are not treated as commands. I'll support this for the next eap.

> `builtin source "${md_executable_directory_path}/../bootstrap/executables.sh"`

I recommend to use ShellCheck directives to handle this:
```bash
# shellcheck source=../bootstrap/executables.sh
source "${md_executable_directory_path}/../bootstrap/executables.sh"
```

The part after `source=` is supposed to have code completion and path support, too. Code completion is currently not working, I'll fix this for the next eap.

Unfortunately, ShellCheck and BashSupport Pro don't support `builtin source` at this time. Only `source` is supported.
Overriding `source` is currently preventing the deeper code insights like following source files and code completion of sources declarations.
I'll put support for `builtin source` on the list for 4.0.

**Comment by NickSdot** [comment]
Thanks again!
