### ISSUE TITLE
(Macro) variables for file paths or file names stopped returning anything

### ISSUE THREAD

**Issue by JohanVandeplas** [BashSupport-Pro/bashsupport-pro#136]
This config used to be working and after updating Intellij a few weeks ago it stopped working.

![image](https://github.com/BashSupport-Pro/bashsupport-pro/assets/1309171/3a65384b-d79b-48a9-b828-357c7f308c7f)

The problem is all path or filename related macro/variable return empty. The preview also confirms the result...

How it used to work. The open/focused file (file name, relative path, dir name, etc depending on what variable you would pick ofc) would be returned.

**I'm using:**
Ubuntu
IntelliJ IDEA 2023.2 (Ultimate Edition) Build #IU-232.8660.185, built on July 26, 2023
BashSupport Pro 3.3.0.232

**Comment by JohanVandeplas** [comment]
Oeps sorry. It seems to be an intellij problem... Node.js tasks act the same way...
![image](https://github.com/BashSupport-Pro/bashsupport-pro/assets/1309171/479db7fb-8665-402c-aa7d-21026315f61a)

**Comment by JohanVandeplas** [comment]
Someone already logged it:

https://youtrack.jetbrains.com/issue/IDEA-326733/Run-configuration-macros-like-FilePath-do-not-work

**Comment by jansorg** [comment]
Thanks for reporting and linking to the YouTrack issue! I‘ll keep an eye on it and hope that it‘s fixed for 2023.2.1.
