### ISSUE TITLE
Top of file constants should not cause warnings

### ISSUE THREAD

**Issue by W-Hamra** [BashSupport-Pro/bashsupport-pro#137]
When using google shell style, I get warnings for top-of-file constants that should otherwise be permitted.

Example code:
```
#!/bin/bash
readonly CONFIG_FILE="/etc/myconfig"
function main() {
  echo
}
main "$@"
```

I get a warning about CONFIG_FILE being outside of main(). But the google shell style guide explicitly [states](https://google.github.io/styleguide/shellguide.html#constants-and-environment-variable-names) that constants should be declared at top of file.

**Comment by jansorg** [comment]
Thanks! You're right, this is a bug. I'll prepare a fix for the next update.

**Comment by jansorg** [comment]
The new 3.3.1 update should fix this issue. Please reopen if you're still seeing incorrect highlighting. Thanks!
