### ISSUE TITLE
Interpolated command is not executing correctly.

### ISSUE THREAD

**Issue by fpga-guy** [BashSupport-Pro/bashsupport-pro#140]

**Comment by jansorg** [comment]
@fpga-guy The description is empty now. Is that intentional?

**Comment by jansorg** [comment]
Please note that BashSupport Pro is currently not supporting zsh, yet.
To debug Zsh, it‘s better to use https://github.com/rocky/zshdb instead of bashdb.

If this issue was meant for BashSupport Pro (e.g. as fromtend to bashdb), please let me know and I‘ll reopen this issue.
Thanks!

**Comment by fpga-guy** [comment]
> @fpga-guy The description is empty now. Is that intentional?

Yes, it was intentional because the original issue was a mistake.
