### ISSUE TITLE
zsh debugging with v 4.0.0.233-beta9

### ISSUE THREAD

**Issue by Maziar123** [BashSupport-Pro/bashsupport-pro#144]
Hi

I am currently trying to debug a zsh script with bashsupport-pro-signed-4.0.0.233-beta9-eap.zip. However, it seems that some simple jobs fail to debug, for example, there is a freeze in one sourced file at this line.
all_ips=$(ip -o -4 addr show | awk '{print $4}')

**Comment by jansorg** [comment]
Thank you for reporting this!
What‘s happening when you observe the freeze? Is the UI of the IDE frozen or is it something else, e.g. is a breakpoint hit?

A screenshot would help to reproduce and fix this.

**Comment by jansorg** [comment]
I'm able to reproduce a problem with "Resume" and stepping through the Zsh script above. I hope to find a fix for the next beta version. Thanks!

**Comment by jansorg** [comment]
This has been fixed in zshdb and the fix will be included with BashSupport Pro's next beta of 4.0.

**Comment by jansorg** [comment]
4.0 beta11 is now available and should fix the problem. Please update here if that‘s not the case for you.
