### ISSUE TITLE
[zsh & perhaps Bash] v4 beta : output tty problem

### ISSUE THREAD

**Issue by Maziar123** [BashSupport-Pro/bashsupport-pro#145]
Hi

1. how set stdin & tty (internal & external ) ?
2. I use this plugin in pycharm when pycharm runs from a Linux terminal (kde konosole) 
 Then Konosole is open when debugging; now my script has some echo 
 (some of it is generated with echo > /dev/tty & some messages without /dev/tty ) 
 nice bug; some messages show in konsole & some messages in your terminal ......

**Comment by jansorg** [comment]
Thanks! zshdb itself is not widely used and BashSupport Pro's integration is also not yet widely used. 
I'll investigate and try to reproduce this.
stdin/stdout/stderr can't be configured, it's supposed to be handled automatically. 

Is there a reason why you're piping to `/dev/tty` instead of just using the default stdout?

**Comment by jansorg** [comment]
Please test with 4.0.2 and let me know when you need further help with this problem. Thanks!

**Comment by Maziar123** [comment]
need extend trial version ...

**Comment by jansorg** [comment]
If you tested 4.0 beta, then you should get a new trial with the final 4.x version. If that's not the case, please write to mail@bashsupport.com.

Please also reply to my question above:
> Is there a reason why you're piping to /dev/tty instead of just using the default stdout?

Thanks!

**Comment by Maziar123** [comment]
_Is there a reason you're piping to /dev/tty instead of just using the default stdout?_
Many times, JetBrains runs from the Linux terminal. Try it! if do it it do piping to  /dev/tty

**Comment by jansorg** [comment]
Are you doing this to see script output executed inside the IDE on the terminal which launched the IDE?
Sorry, but I still don't understand the use case.

**Comment by Maziar123** [comment]
Sorry, I wonder what is not understandable.

In Linux, many times, also in x, you run tools that use the terminal, for example, to set variables or paths...

**Comment by jansorg** [comment]
@Maziar123 Sorry, but I just don't understand your use-case and wanted to understand it before I decide if this should or could be implemented.

> how set stdin & tty (internal & external ) ?

STDIN can be set for run configurations to a file, see setting "Redirect from input:" at https://www.bashsupport.com/manual/run/settings/#configuration

`/dev/tty` is [the controlling terminal](https://stackoverflow.com/questions/8514735/what-is-special-about-dev-tty). 
Executing `tty` prints the terminal connected to STDIN (`man tty`).

The BashSupport Pro run configurations are creating a new controlling terminal, so `echo something > /dev/tty` prints to the output tool window of the run configuration, which is the same as `echo something` unless another redirection is applied for this command in the script.
Currently, `/dev/tty` is unavailable in a debug session (I don't know why, yet).

For `echo something > /dev/tty` where would you like to see the output? 

If you have a specific use-case to use `/dev/tty` please post a sample script to demonstrate this.
