### ISSUE TITLE
License Questions

### ISSUE THREAD

**Issue by WHUT-XQH** [BashSupport-Pro/bashsupport-pro#146]
The license I first purchased expired on 2023/12/28, I reactivated it on 2024/01/11 and repurchased it for 1 month, why did the new license expire on 2024/01/28 instead of 2024/02/11

**Comment by jansorg** [comment]
AFAIK the new purchase is starting at the day the previous subscription expired. For details please reach out to https://www.jetbrains.com/support/sales/#email-sales, it may be possible to change your license.

**Comment by WHUT-XQH** [comment]
> AFAIK the new purchase is starting at the day the previous subscription expired. For details please reach out to https://www.jetbrains.com/support/sales/#email-sales, it may be possible to change your license.

Thank you for your reply, if so, if my license has expired for a month and renewed for a month, is it not available for a day?（
Forgive me for the first time using a paid plug-in）

**Comment by jansorg** [comment]
@WHUT-XQH I've reached out to JetBrains for clarification, I'll update this thread when I have a reply.

**Comment by jansorg** [comment]
@WHUT-XQH Apologies for the late reply.
The backdating of the 2nd purchase happens for an uninterrupted history for the free fallback license after 12 months of uninterrupted payment and also for the discounts which are applied in the 2nd year and later.
According to JetBrains, a purchase 30 days later should not be backdated (i.e. 30 days validity and not just one). But they couldn't tell me after which period of inactivity this happens.
Please reach out to mail@bashsupport.com if this happens unexpectedly for you after such a purchase.
