### ISSUE TITLE
Default Idea "Shell Script" stop working after removing "Bash Support Pro"

### ISSUE THREAD

**Issue by Kolyall** [BashSupport-Pro/bashsupport-pro#149]
Steps:
- Run Android Studio
- Install "Bash Support Pro"
- Restart Android Studio
- Close purchase dialog --> "Bash Support Pro" becomes disabled
- Restart Android Studio
- Enable "Shell Script"
- Uninstall "Bash Support Pro" 

[result]
- Default Idea "Shell Script" stop working. Can't run any sh file. by clicking on Run icon in file

**Comment by jansorg** [comment]
Unfortunately, that's a bug in the platform JetBrains hasn't fixed yet.
Uninstalling the plugin should have shown this page, which has instructions to fix this: https://www.bashsupport.com/uninstalled#reset-extensions
Please let me know if that doesn't work for you.

The latest version 3.3.6 attempts to fix this automatically, but apparently that failed on your setup. I'll try to find a way to make this work when it's disabled from the purchase dialog.
