### ISSUE TITLE
New Shell project doesn't work in PyCharm

### ISSUE THREAD

**Issue by wellic** [BashSupport-Pro/bashsupport-pro#150]
Creating new project for shell doesn't work in PyCharm but work in IntelliJ.

**Comment by jansorg** [comment]
Thanks for reporting! PyCharm seems to work differently with generic projects, I'll try to solution compatible with all JetBrains products.

**Comment by wellic** [comment]
I'm devops and I often works with python and bash. It's important for me.
Thanks.

**Comment by jansorg** [comment]
I've found a way to make it work and will publish it soon with update 4.0.2.
It's always possible to just create bash scripts inside a python project, creating a new shell project is only a user-friendly way to set up a new project with UI.

**Comment by jansorg** [comment]
BashSupport Pro 4.0.2 is now available with a fix for this.

Make sure to click "More Settings" to see all. Unfortunately, this is the only way to convince PyCharm (and other non-IntelliJ products) to allow this :( 
![image](https://github.com/BashSupport-Pro/bashsupport-pro/assets/11473063/b1f26504-b582-41ec-b6e8-27644bd18ae4)
