### ISSUE TITLE
Can't run. Error Access is allowed from Event Dispatch Thread (EDT) only

### ISSUE THREAD

**Issue by Kolyall** [BashSupport-Pro/bashsupport-pro#152]
```
Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details Current thread: Thread[JobScheduler FJ pool 0/11,4,main] 942881693 (EventQueue.isDispatchThread()=false) SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1081692216
```
After clicking on "Run in terminal"
![image](https://github.com/BashSupport-Pro/bashsupport-pro/assets/3495165/cd531f12-b435-4c60-9160-d32c9fa6ffea)

**Comment by jansorg** [comment]
I'm sorry, this is a regression of the latest 4.0.2 update. I'll publish a fix shortly.

**Comment by jansorg** [comment]
Update 4.0.3 is now available with a fix. Thanks for reporting!
