### ISSUE TITLE
Using macros $Prompt$ or $FilePrompt$ in Run configuration get and error

### ISSUE THREAD

**Issue by valdemar1977** [BashSupport-Pro/bashsupport-pro#155]
Get error when run a script "Error running 'main.bash' Invalid run configuration: Calling invokeAndWait from read-action leads to possible deadlock" if using macros `$Prompt$` or `$FilePrompt$ `in Run configuration
Debug stared ok.
MacOS Ventura CLion 2024.1.1  BashSupportPro 4.0.3.241

**Comment by jansorg** [comment]
Thanks!
By coincidence, I fixed this today. Macros using UI and macros using the current file are fixed for the next update.
Run configs are a complex piece of the SDK, but things should be better with the next update...

**Comment by jansorg** [comment]
Version 4.1.1 with the fixes is now available.
