### ISSUE TITLE
In bash, ${diskSize:=0} is a variable assignment and default value setting command, but it is not recognized properly?

### ISSUE THREAD

**Issue by super-vip** [BashSupport-Pro/bashsupport-pro#156]
![image](https://github.com/BashSupport-Pro/bashsupport-pro/assets/19517568/0e3eb92a-c3cf-497f-b731-93079e8df058)

**Comment by jansorg** [comment]
I can confirm that this is a bug. I'll fix it for the next update.
It's happening because `${diskSize:=0}` is inside a subshell and here BashSupport Pro is not applying the correct scoping.

The following works as expected:
```bash
diskSize=42
echo ${diskSize:=0}
```

**Comment by jansorg** [comment]
This is fixed now for the next update

**Comment by super-vip** [comment]
![image](https://github.com/BashSupport-Pro/bashsupport-pro/assets/19517568/840ddfb0-23c9-4510-b4aa-1c47a7acdc50)
Inline arrays seem to have this problem?

**Comment by jansorg** [comment]
@super-vip Yes, unfortunately that's a known issue. As a workaround, please quote the keys, e.g. `["red"]`.
(Please create new issue if it's not related to the current issue)

Bash determines at runtime how to interpret `[red]`. For indexed arrays, it's an arithmetic expression (and `red` would be a variable) and for associative arrays `red` is a string value.

Here's an example:
```bash
#!/usr/bin/env bash
red=1
declare -a colorsIndexed
declare -A colorsAssociative
colorsIndexed=(
    [red+10]="this is red+10"
)
colorsAssociative=(
    [red+10]="this is red+10"
)
declare -p colorsIndexed
declare -p colorsAssociative
```

Output:
```text
declare -a colorsIndexed=([11]="this is red+10")
declare -A colorsAssociative=([red+10]="this is red+10" )
```

**Comment by jansorg** [comment]
Version 4.1.1 with the fix for the parameter expansion is now available.

**Comment by super-vip** [comment]
Great, thank you. Upon testing, it has been confirmed that this issue has been resolved.
