### ISSUE TITLE
Your certificate has expired today!!

### ISSUE THREAD

**Issue by dgor82** [BashSupport-Pro/bashsupport-pro#160]
See screenshot. 
<img width="597" alt="Screenshot 2024-05-13 at 11 14 18" src="https://github.com/BashSupport-Pro/bashsupport-pro/assets/41432066/033b628b-f2d0-4b8b-af9b-fcc370d3a6e0">

**Comment by jansorg** [comment]
Thanks, I'm  already on it. self-hosting :(

**Comment by jansorg** [comment]
Fixed. Thanks for reporting!
