### ISSUE TITLE
Unable to Debug Zsh Script

### ISSUE THREAD

**Issue by sassdavid** [BashSupport-Pro/bashsupport-pro#161]
Environment
- Operating System: Windows 11
- WSL Distribution: Ubuntu 24.04
- Shell: Zsh
- IDE: IntelliJ IDEA 2024.1.1
- Plugin: BashSupport Pro 4.0.3.241

While attempting to debug a Zsh script using the BashSupport Pro plugin in IntelliJ IDEA, the process fails with the message below. The script terminates with an exit code of 1, and the usage instructions are displayed, indicating that not all required options were provided, it's weird because I provided all the required parameters.

```
C:\WINDOWS\system32\wsl.exe -d Ubuntu-24.04 -e zsh /mnt/c/Users/sassd/AppData/Roaming/JetBrains/IntelliJIdea2024.1/plugins/bashsupport-pro/zshdb/zshdb --quiet --no-highlight --library /mnt/c/Users/sassd/AppData/Roaming/JetBrains/IntelliJIdea2024.1/plugins/bashsupport-pro/zshdb/share/zshdb --tty /mnt/c/Users/sassd/AppData/Local/Temp/bashsupport-zshdb.log /home/sassd/src/bitbucket/loxon/sassd/loxon-charts/deploy_charts.zsh -- -a <aws-account-id> -p <aws-profile> -r <aws-region> -u
[3[83;82;;22;5253;88;32;5151;22m55m[0[39mm** /mnt/c/Users/sassd/AppData/Local/Temp/bashsupport-zshdb.log is not reputed to be a tty.
(/home/sassd/src/bitbucket/loxon/sassd/loxon-charts/deploy_charts.zsh:3):
set -e
All options must be provided.
Usage: print_usage -a <aws-account-id> -p <aws-cli-profile> -r <aws-region> [-u]
Debugged program terminated with code 1. Use q to quit or R to restart.

Process finished with exit code 1
```

Please let me know if you need any further information to investigate the issue. Also, please inform me if I did not follow your guidelines for reporting an issue.

**Comment by jansorg** [comment]
Thanks for reporting!
It's very likely a problem with the debugger and/or Zsh on Windows WSL. Unfortunately, debugging with Zsh on Windows isn't working well (I though I had documented this, but can't find it right now). Windows itself is problematic for debugging Bash, but Zsh seems to be more problematic. I'll try again to find out what's wrong...

Are you running your IDE on Windows or via Gateway inside WSL?

**Comment by sassdavid** [comment]
Thanks for the prompt response.

Yes, as I remember, I haven't found related documentation for this; that's why I tried to use it.

I'm running the IDE on Windows and opening my project from the WSL. I imagine it could work through Gateway because I previously experienced something similar with LLVM, which worked through Gateway but not on Windows with an open project from WSL.

Thank you in advance for the further checking on this.

**Comment by jansorg** [comment]
I've found a problem, that zshdb interprets the argument to introduce script args `--` as actual script argument. I'm currently looking at this and should be able to fix this for the next update.
I suppose that the additional `--` which is passed to the command balled inside your script is confusing it.

**Comment by sassdavid** [comment]
Thanks for the fast investigation.

I don't pass the double dash consciously (`--`) as an argument; most probably, Windows or WSL does. I've found a related discussion: https://discuss.bashsupport.com/t/bashsupport-pro-with-jetbrains/155.

The situation is the same in terms of bashdb debug, but that works correctly with the double dash (`--`).

I'm going to check whether the double dash can be avoided or not. In the meantime, thank you for trying to find a possible fix for it.

**Comment by jansorg** [comment]
The plugin is passing the `--`.
`man bash` says that Bash is supporting this to stop its own argument processing. `man zsh` doesn't mention it, so it's most likely a bash-only feature. For the next update, `--` will not be added when debugging with Zsh.

On my setup, basic debugging on Windows 11 is working okay with the fix. 
Due to limitations of Windows and zshdb, the script's STDOUT/STDERR is shared with the debugger input/output (but only on Windows), but the debugger UI is not impacted by this limitation. I hope to find a workaround for this, but currently there's none.

**Comment by sassdavid** [comment]
Oh, thanks, clear.

I'm looking forward to the fix.

Thanks for your help.

**Comment by jansorg** [comment]
Version 4.1.1 with a fix is now available.
