### ISSUE TITLE
Running bats-core tests gives different result inside IDE and outside

### ISSUE THREAD

**Issue by jappievw** [BashSupport-Pro/bashsupport-pro#17]
When I'm running tests inside the IDE, it often reports the wrong line failing. It's always the first line before the actual one failing. For example:

```
#!/usr/bin/env bats

the_actual_function() {
    echo "${1}"
}

@test "some cool test" {
    run the_actual_function "with an argument"
    
    [[ "$status" -eq 0 ]]
    [[ "$output" =~ an\ argument\ yo$ ]] 
}
```

Running this test via the IDE shows the following result:
```
Testing started at 12:49 ...
/usr/local/bin/bash "/Users/my-user/Library/Application Support/Rider2019.3/bashsupport-pro/bats-core/bin/bats" -t -f ^some[[:space:]]+cool[[:space:]]+test$ -r /Users/my-user/development/amzn2-netcore-showcase/scripts/codedeploy/lib/tests/dotenv.bats
   ---
   # (in test file dotenv.bats, line 10)
   #   `[[ "$status" -eq 0 ]]' failed
   ...

some cool test
```

Running it via my regular terminal gives the proper failure:
```
   ---
   # (in test file /Users/my-user/development/amzn2-netcore-showcase/scripts/codedeploy/lib/tests/dotenv.bats, line 11)
   #   `[[ "$output" =~ an\ argument\ yo$ ]] ' failed
   ...
```

**Comment by jansorg** [comment]
Thanks! Could you post the the OS you're using, the output of `bash --version` and the output of `bats-core --version` (or what you're using to run in in a terminal)?
BashSupport Pro uses a slightly modified version of bats-core to enable better integration with the UI.

**Comment by jappievw** [comment]
I'm using the packaged version both within the IDEA and the command line, to ensure there are no version differences.

Running macOS `10.15.4 (19E266)`

```
$ /usr/local/bin/bash --version
GNU bash, version 5.0.16(1)-release (x86_64-apple-darwin19.3.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by jansorg** [comment]
I was able to reproduce this. Old versions of Bash are reporting an incorrect line number.
The terminal uses zsh, most likely with `/usr/local/bin/bash` in `$PATH`, which is Bash v5.
bats-core, which is started by IntelliJ doesn't have that in path and ends up with `/bin/bash`, which is the old version. And that gives you the wrong line number.
I should have a fix for this with the next update.

**Comment by jansorg** [comment]
@jappievw This is a very weird error.
Could you add `PATH=/usr/local/bin:/usr/bin:/bin` to the input field "Environment variables" of your bats-core run configuration? If I'm not mistaken, then you should see the right number with this setup. If that succeeds, then could you try this with your other failing test, too?
I'll patch this with the next update, so that you don't need this manual override.

**Comment by jappievw** [comment]
I just validated this behaviour. When I add this path env var, it works exactly the same. I'll keep it in there for now! Good find!

**Comment by jappievw** [comment]
Works exactly the same means exactly equal to in my regular terminal.

**Comment by jansorg** [comment]
Update 1.2.4 was just published with a fix for this issue. This should be working now without the override of `$PATH`.

**Comment by jappievw** [comment]
Thanks a lot. Works like a charm! (both issues I opened)
