### ISSUE TITLE
Run configuration type Shell Script is unknown when BashSupport Pro is enabled

### ISSUE THREAD

**Issue by thilken** [BashSupport-Pro/bashsupport-pro#170]
Within a project we have run configurations that we combine using the [Multirun plugin](https://plugins.jetbrains.com/plugin/7248-multirun/). We use it to ensure a specific order in that the configurations are run. This works fine in general. The issue is when I add a run configuration for a shell script that is created by BashSupport Pro resulting in the following run configuration xml:

`
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="App startup" type="Multirun" separateTabs="false" reuseTabsWithFailures="false" startOneByOne="true" markFailedProcess="true" hideSuccessProcess="false" delayTime="0.0">
    <runConfiguration name="mock" type="Spring Boot" />
    <runConfiguration name="services" type="Spring Boot" />
    <runConfiguration name="import-data-to-db-container.sh" type="Shell Script (by BashSupport Pro)" />
    <method v="2">
      <option name="RunConfigurationTask" enabled="true" run_configuration_name="compose" run_configuration_type="ShConfigurationType" />
    </method>
  </configuration>
</component>
`

The issue with that is that the type="Shell Script (by BashSupport Pro)" is unsupported for my collegues that do not have BashSupport pro. For them it needs to be type="Shell Script" in order to run correctly. When I change this manually within the XML file than the line is automatically removed and for me it does not work. I also tried to have the original JetBrains Shell integration enabled together with BashSupport Pro, but that also does not help. The reason is that a JetBrains run configuration is automatically moved into a BashSupport pro configuration type.

It would be great when I would be able to use the type="Shell Script" with BashSupport pro.

Thanks in advance for any support

**Comment by jansorg** [comment]
Thanks for reporting!
I've tested this with Multirun and can confirm your findings.

I've submitted a bug report to Multirun because it's a problem of that plugin. It's using a non-unique UI display string to reference run configurations. "Shell Script (by BashSupport Pro)" is the display string.
https://github.com/rkhmelyuk/multirun/issues/103

I hope that the author is responsive to accept a PR and to publish a new release.
I'd like to not change "Shell Script (by BashSupport Pro)" to "Shell Script" because that might break other plugins, if there's another plugin like Multirun.

**Comment by jansorg** [comment]
Unfortunately, the author of the Multirun  plugin doesn't reply. I'll probably change the display name for the next major version. I could add a registry flag for the next update of 4.x if you'd like to be able to test the change earlier.

**Comment by jansorg** [comment]
I'm going to fix this for 4.3.0, which is going to be released soon.
The display name will be "Shell Script" as long as the JetBrains Shell plugin is not enabled at the same time as BashSupport Pro.

**Comment by jansorg** [comment]
Version 4.3.0 with a fix is now available. Please let me know if the fix is not satisfactory.
