### ISSUE TITLE
Debugger console font oddity

### ISSUE THREAD

**Issue by bedge** [BashSupport-Pro/bashsupport-pro#174]
I'm not a font snob but this is just hard to read:
![image](https://github.com/user-attachments/assets/5c13eeae-bc9a-4acb-90bd-5c09920a70fe)

Is there somewhere I can change this?
General intellij complaint - difficult to find the settings context to change the thing you don't like. 

Apologies if this isn't related to your excellent plugin.

**Comment by bedge** [comment]
IntelliJ IDEA 2024.2.0.1 (Ultimate Edition)
Build #IU-242.20224.387, built on August 13, 2024
Licensed to XXXX
Subscription is active until December 31, 2024.
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 32
Registry:
  ide.balloon.shadow.size=0
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  color.scheme.Derwish Theme13 (0.3)
  MultiHighlight (3.2.0)
  org.intellij.plugins.hcl (242.20224.159)
  PythonCore (242.20224.300)
  com.mrootx.idea (1.0.2)
  com.github.b3er.idea.plugins.arc.browser (0.32)
  de.nordgedanken.auto_hotkey (0.10.4)
  awesome.console (0.1337.12)
  EclipseCodeFormatter (23.4.223.000.0-Eclipse_2023-03)
  AntSupport (242.20224.159)
  com.ahmed3elshaer.true-black-theme (1.4.5)
  Pythonid (242.20224.387)
  com.intellij.plugin.adernov.powershell (2.6.1)
  com.intellij.mermaid (0.0.22+IJ.232)
  GrepConsole (13.1.0-IJ2023.3)
  com.intellij.ml.llm (242.20224.393)
  PlantUML integration (7.10.1-IJ2023.2)
  pro.bashsupport (4.2.2.242)
  com.yiycf.plugins.mavenDependencyHelper (2.5)
  MavenRunHelper (4.28.0-IJ2022.2)
  com.intellij.bigdatatools.core (242.20224.387)
  com.intellij.bigdatatools.binary.files (242.20224.159)
  com.intellij.bigdatatools.rfs (242.20224.387)
  com.datadog.intellij (1.5.1)
  com.github.copilot (1.5.19.6527)
  com.chrisrm.idea.MaterialThemeUI (9.4.1)
  zielu.gittoolbox (500.2.14+242)
Kotlin: 242.20224.387-IJ

**Comment by jansorg** [comment]
That's very weird, almost as if there's extra whitespace between the characters. Is that perhaps the case?

Is the regular terminal of the IDE looking the same way?

I'll be able to investigate this early next week...

**Comment by jansorg** [comment]
According to the web help, the setting is here:
> On the Editor | Color Scheme | Console Font page, you can configure line spacing and fonts.

AFAIK the theme can also change it.

BashSupport Pro does not customize the font, but things with the terminal can be odd sometimes...

**Comment by bedge** [comment]
No extra space. A copy/paste into some other target shows no extra chars.
New beta fixed it. Sorry for the ticket spam. It's getting harder to figure out the chain of ownership with this stuff. 
Thank you again.
