### ISSUE TITLE
Language Display Issue

### ISSUE THREAD

**Issue by piromix** [BashSupport-Pro/bashsupport-pro#176]
Hi,
I used to see the settings displayed in English when using an English environment, but now they are showing up in Chinese. How can I change the settings back to English?

**Comment by jansorg** [comment]
Hi,
are you a Chinese-speaking user with an English setup or is the rendering in Simplified Chinese totally unexpected?

Which IDE and version are you using? (Or just paste the output of `Help > About > Copy`)
If possible, please share a screenshot.

In 2024.2, the language can now be controlled at `Settings > Appearance & Behavior > System Settings > Language and  Region`. If this doesn't work correctly with BashSupport Pro, I'll fix it.

**Comment by piromix** [comment]
I don't speak or understand Chinese, so seeing the display in Simplified Chinese was completely unexpected.

Here is my IDE information:
```
IntelliJ IDEA 2024.2.0.1 (Ultimate Edition)
Build #IU-242.20224.387, built on August 13, 2024
Licensed to XXX
You have a perpetual fallback license for this version.
Subscription is active until September 2, 2025.
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.2.0-39-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 24
Registry:
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  documentation.show.toolbar=true
  light.edit.file.open.enabled=false
  ide.experimental.ui=true
  scala.erase.compiler.process.jdk.once=false
  llm.inline.completion.log=true
Non-Bundled Plugins:
  com.intellij.javafx (1.0.4)
  com.fwdekker.randomness (3.3.1)
  com.samuraism.plugins.kasumi (1.6.0)
  wallaby.js (1.0.292)
  quokka.js (1.0.454)
  com.devoxx.genie (0.2.14)
  org.intellij.RegexpTester (2.2.0)
  com.intellij.grazie.pro (0.3.326)
  com.paperetto.dash (3.3)
  org.jetbrains.projector-plugin (1.11.2)
  com.github.nizienko.SpaceInvaders (1.1.0)
  com.intellij.plugins.watcher (242.20224.155)
  com.jetbrains.space (242.20224.155)
  com.chylex.intellij.inspectionlens (1.4.1)
  PlantUML integration (7.10.1-IJ2023.2)
  String Manipulation (9.14.1)
  de.docs_as_co.intellij.plugin.diagramsnet (0.2.6)
  AceJump (3.8.19)
  IdeaVIM (2.16.0)
  org.jetbrains.IdeaVim-EasyMotion (1.15)
  com.joshestein.ideavim-quickscope (1.0.12)
  com.intellij.mermaid (0.0.22+IJ.232)
  GrepConsole (13.1.0-IJ2023.3)
  com.samuraism.plugins.tiger (2024.1.0)
  com.intellij.ml.llm (242.20224.419)
  com.majera.intellij.codereview.bitbucket (2024.2.4.242)
  uk.co.ben-gibson.remote.repository.mapper (4.4.0)
  mobi.hsz.idea.gitignore (4.5.3)
  com.jetbrains.plugins.jade (242.20224.159)
  com.github.copilot (1.5.20.6559-nightly)
  com.laravel_idea.tailwind (1.4.2)
  org.intellij.prisma (242.20224.159)
  com.intellij.lang.jsgraphql (242.20224.155)
  com.haulmont.rcb (242.20224.155)
  com.virtuslab.git-machete (5.0.1)
  com.jetbrains.php (242.20224.387)
  com.clutcher.comments_highlighter (2024.1.34)
  com.laravel_idea.plugin (8.2.4.242)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  pro.bashsupport (4.2.2.242)
  org.exbin.deltahex.intellij (0.2.10.1)
  com.eny.i18n (2.6.2)
  zielu.gittoolbox (500.2.14+242)
  org.intellij.scala (2024.2.20)
  com.samuraism.plugins.mito (2024.1.0)
  cn.yiiguxing.plugin.translate (3.6.4)
  codiumai.codiumai (0.9.3)
  dev.nx.console (1.28.3)
Kotlin: 242.20224.387-IJ
Current Desktop: ubuntu:GNOME
```


Additionally, the language setting in `Language and Region` was set to English.
There was a recent update to the IDE, so that might be affecting it.

**Comment by jansorg** [comment]
Thanks, I'll investigate and will keep you updated.

**Comment by jansorg** [comment]
@piromix Unfortunately, I was unable to reproduce this with the same version and a bunch of the plugins you installed.
It's possible that another plugin is changing the IDE's language settings.

Do you mind to execute "Settings > Plugins > Gear wheel icon > Disable all downloaded plugins" and restart and check if the settings are still in Chinese?

2024.2 changed a few things in regard to the language settings. If the above doesn't help, then I'll prepare a preview with a change with a slightly better integration with the new changes of 2024.2, even though I'm unable to reproduce this.

Thanks!

**Comment by jansorg** [comment]
@piromix I've published a preview build at https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/edit/versions/eap/591077 . It should hopefully fix the display issues you're seeing, even though I'm still unable to reproduce it. It's adapted to use 2024.2 advanced capabilities to handle translations.

1. Download the ZIP file
2. Install with `Settings > Plugins > Gear wheel icon > Install from disk`
3. Restart
4. I'd appreciate if you could let me know if this is fixing the problem for you

**Comment by piromix** [comment]
@jansorg Thank you for providing the preview build. 
I downloaded and tested it, and the display has reverted to English.

Thank you for addressing the issue.

**Comment by jansorg** [comment]
Thank you for your feedback, I'm glad it's working now!
4.2.4 has been published on the stable channel now.
