### ISSUE TITLE
Quick Documentation stopped working

### ISSUE THREAD

**Issue by SergeySevbitov** [BashSupport-Pro/bashsupport-pro#178]
Hi @jansorg,

At certain point after many BSP/PyCharm updates I noticed that Quick Documentation stopped working, including standard functions like `echo` or `export` mentioned in the documentation.

Is there any way to reset or configure it?

```PyCharm 2024.2.1 (Community Edition)```
```BashSupport Pro 4.2.4.242```

Thanks!

**Comment by jansorg** [comment]
@SergeySevbitov Thanks for reporting!
Which OS are you using?
Is quick documentation for variables like `$HOME` still  working?
Do you have set up a Bash interpreter at `Settings > Languages & Framework > BashSupport Pro > Shell Interpreters`?

Quick documentation for commands uses `help`, `man` or `info`. `help` with the configured, default Bash interpreter is used for Bash's own commands like `echo`.

**Comment by SergeySevbitov** [comment]
It is Windows 11. I have the following interpreters, which were detected automatically: `WSL(2)`, `Git Bash (MSYS)`, `Cygwin`.
If I launch `wsl.exe -e bash man man` in `cmd`, it shows a manual.
`Git Bash` doesn't have `man`, only `help`.
`Cygwin` has `man-db` package installed, but a default entry like `C:\cygwin64\bin\bash.exe` does not load Bash env, thus `man` is not found. Instead, it should go with `--login` or a path to a default env/rc.

Anyway, in BashSupport Pro with PyCharm, when I hit Quick Documentation it hangs for a while, then says `No documentation`.

Could it be the issue with the output redirection? or timeout or smth? I noted that any `wsl.exe` command are somewhat sluggish.

The case is not very important though, more of a curiosity.

**Comment by jansorg** [comment]
Thanks for the feedback! I'll investigate this. But my guess is that it's either a timeout with the slow WSL command (the first Bash interpreter is used to invoke `help`) or a bug/problem on Windows in general.

**Comment by jansorg** [comment]
Is `mandoc` installed in your WSL distribution? `apt install mandoc` should do it.
The plugin currently uses a few tools to convert the man page into HTML: `man`, `zcat`, `mandoc` and `groff`.

**Comment by jansorg** [comment]
The next update (4.3) will contain a few fixes to work better with Windows 11. It's working on my Windows 11 setup, please let me know if the new version is still not showing man page documentation on your system.

**Comment by jansorg** [comment]
Version 4.3.0 with a fix is now available. Please let me know if the fix is not satisfactory.

**Comment by SergeySevbitov** [comment]
@jansorg Thank you, it is working now!
