### ISSUE TITLE
Inline Snippet Seems To Not Support Debug

### ISSUE THREAD

**Issue by emmahyde** [BashSupport-Pro/bashsupport-pro#179]
whenever I use an inline snippet instead of a file, my `debug` icon greys out and I don't appear to be able to use it. 
![Screenshot 2024-09-18 at 15 33 50](https://github.com/user-attachments/assets/c2894bbc-5fcf-4bc8-91ba-c24d42af2c41)
This never used to happen – what am I doing wrong? It breaks debug for my compound command that includes it, which has been working for at least a year. I'd be perfectly happy if it just ran as usual and the other configs in the compound command went into debug, but it seems to disable it for the entire compound command.

**Comment by emmahyde** [comment]
I tried this on RubyMine 2024.2.1, 2024.2.2 RC, and 2024.2.3 EAP.
![Screenshot 2024-09-18 at 15 35 53](https://github.com/user-attachments/assets/5eeb3e1d-2cfd-4342-9709-0d7d8d6f53b7)
<img width="392" alt="Screenshot 2024-09-18 at 15 35 51" src="https://github.com/user-attachments/assets/7fb1711e-8b9e-42b5-8566-4bd9c1b13ff5">
I wish it would at least give an indicator as to what is not working!

**Comment by jansorg** [comment]
Thanks for reporting!
Could you show a screenshot of the run configuration settings, please?

Debugging of an inline shell script snippet has never been supported so far, in any version.
I'll double-check if the button was enabled previously. The screenshot would allow me to reproduce what you'd like to achieve.

**Comment by emmahyde** [comment]
interesting. ok, maybe its because of the pivot to bash support pro. I will likely stop paying for the service, though – my one-click debugging env is critical to my flow! It definitely was fine before but it may have been on jetbrains shell plugin instead. Here are the run config settings: 
![Screenshot 2024-09-18 at 16 33 28](https://github.com/user-attachments/assets/72817929-6e63-41dc-903c-792c9308bd96)

**Comment by jansorg** [comment]
Thanks.
To understand the setup: is there another, compound run configuration, which references this shell script configuration and you would like to run "debug" for the compound run configuration to launch all included run configurations in debug mode if it's supported?

BashSupport Pro should certainly not make things worse compared to JetBrains Shell. I'll check if support for a compound setup is possible, if that's your use case.

**Comment by emmahyde** [comment]
Yes, that's correct!

Even just running the job alone, I can no longer "launch" it in debug mode, and it prevents the compound job from running in debug mode... In reality, I just need the OTHER configs in the compound job to run in debug, and don't need this job to do anything other than not PREVENT me from the attempt, if that makes sense.

**Comment by jansorg** [comment]
Thanks!
I'm able to reproduce the problem you described.

JetBrains Shell just enabled the debug button without any debugging support at all.

I'm preparing a fix for the next update to enable debug mode for run configurations using a snippet. The snippet is copied to a temporary file before the shell debugger is launched for the new temp file. Even though breakpoints inside the snippet (temp file) are not yet supported, this will not prevent compound run configurations to run.

Unfortunately, it's not possible to only enable the debug button for compound run configurations.

**Comment by emmahyde** [comment]
This is awesome, thank you! I can't wait!

**Comment by jansorg** [comment]
I'll update this issue when the new update is out.
Are you using snippets with run targets, i.e. remote bash execution?

**Comment by jansorg** [comment]
Version 4.3.0 with a fix is now available. Please let me know if the fix is not satisfactory.
Snippet debugging is supported for local execution and for run target execution, too.
