### ISSUE TITLE
Test framework quit unexpectedly when there is a syntax error in the test

### ISSUE THREAD

**Issue by jappievw** [BashSupport-Pro/bashsupport-pro#18]
Given the following test;
```
#!/usr/bin/env bats

the_actual_function() {
    echo "${1}"
}

@test "some cool test" {
    run the_actual_function "with an argument"
    
    [[ "$status" -eq 0 ]]
    [[ "$output" =~ an\ argument yo$ ]] 
}
```

Running this via the IDEA results in a `Test framework quit unexpectedly`.
<img width="586" alt="image" src="https://user-images.githubusercontent.com/718437/78776533-481be900-7998-11ea-8572-e0f30bd3e607.png">

Running it via the command line results in an actionable error:
```
1..1
/var/folders/hh/q1qf23ls67lgc1vs3y7yrm200000gp/T/bats.97622.src: line 11: syntax error in conditional expression
```

**Comment by jansorg** [comment]
Thanks! BashSupport Pro could display a notification with the message about the syntax error instead of terminating unexpectedly. Does that sound okay to you?

**Comment by jappievw** [comment]
That sounds like a very great feature!

**Comment by jansorg** [comment]
bats-core output to stderr wasn't properly displayed. The next update will properly display this kind of text.
The error message will be printed in red in the panel on the right.

**Comment by jappievw** [comment]
Cool! I'm glad you found the issue here. The solution sounds amazing and will be really helpful for the workflow!

**Comment by jansorg** [comment]
Update 1.2.4 was just published with a fix for this issue.
