### ISSUE TITLE
The shell script editing window randomly disappears

### ISSUE THREAD

**Issue by mylovesaber** [BashSupport-Pro/bashsupport-pro#182]
The shell script editing window randomly disappears, and double-clicking the script in the left-hand project tree does not open it. I have to go to:
Files - Invalidate Caches... - select "Clear file system cache and Local History" 

in IDEA and then restart IDEA to reopen the previously inaccessible script. 

Additionally, the crash rate increases if the shell script does not use the .sh extension. IDEA does not display any error messages, so I don't know how to collect logs for this sudden inability to open. This bug has existed for an unknown period, and I'm unsure whether it's a problem with JetBrains or bash support pro.

**Comment by mylovesaber** [comment]
I found a new but strange way to trigger this bug:
```shell
#!/bin/bash
echo "正在终止 internal-sftp 进程..."
processList=()
mapfile -t -O "${#processList[@]}" processList < <(pgrep -f internal-sftp)
if for i in "${!processList[@]}" ; do
    printf '\r总数: %d / 清理进度: %d' "${#processList[@]}" "$((i + 1))"
    kill -9 "${processList[${i}]}"
done; then
    echo -e "\n终止 internal-sftp 进程成功"
fi

echo "正在终止 nclink 进程..."
processList=()
mapfile -t -O "${#processList[@]}" processList < <(pgrep -f nclink)
if for i in "${!processList[@]}" ; do
    printf '\r总数: %d / 清理进度: %d' "${#processList[@]}" "$((i + 1))"
    kill -9 "${processList[${i}]}"
done; then
    echo -e "\n终止 nclink 进程成功"
fi
unset processList

echo "清理完成"

父函数中的局部变量在子函数中引用时无法被解析

f1是入口函数，f2、f3、f4是其子函数，我在f1函数中声明了一个局部变量aa和bb并赋值，之后在f2、f3、f4函数中进行调用
aa和bb的功能区别在于：
- aa是显式传入子函数，并在内部进行调用
- bb是以继承的方式在子函数中调用，



f1() {
    local aa bb
    aa=2
    bb=3
    f2 "${aa}"
    f3
    f4
}
f2() {
    local cc
    aa="${1}"
    echo "aa=${aa}"
    cc="${1}"
    echo "cc=${cc}"
}
f3() {
    f4
}
f4() {
    echo "bb=${bb}"
}
f1
f1() {
    local aa bb
    aa=2
    bb=3
    f2 "${aa}"
    f3
    f4
}
f2() {
    local cc
    aa="${1}"
    echo "aa=${aa}"
    cc="${1}"
    echo "cc=${cc}"
}
f3() {
    f4
}
f4() {
    echo "bb=${bb}"
}
f1


f1() {
    local aa bb
    aa=2
    bb=3
    f2 "${aa}"
    f3
    f4
}
f2() {
    local cc
    aa="${1}"
    echo "aa=${aa}"
    cc="${1}"
    echo "cc=${cc}"
}
f3() {
    f4
}
f4() {
    echo "bb=${bb}"
}
f1


```

In IDEA, new - shell script.
file name for example:  aa.sh

then paste  the  whole  code above into  editor.  The  editor for this script  will disappear  at once. However, When I delete any code. I couldn't trigger this bug happen...

**Comment by jansorg** [comment]
Thanks! I'm able to reproduce this and it's a very weird bug...
I'm still investigating this and I'm not seeing any error message. I'll let you know if it's a bug I can fix or if it's something in the JetBrains products...

**Comment by mylovesaber** [comment]
> Thanks! I'm able to reproduce this and it's a very weird bug... I'm still investigating this and I'm not seeing any error message. I'll let you know if it's a bug I can fix or if it's something in the JetBrains products...
"

I first encountered the issue of the editor window automatically closing at least three years ago when I initially installed BSP in IDEA to write shell scripts. It happened once or twice, and I didn't think much of it. However, I've encountered this problem intermittently over the past three years, but since it was difficult to reproduce consistently, I haven't reported it to you. Today, I've finally found a scenario that almost always triggers this issue.

If this problem can be resolved, I would appreciate it if you could also look into another, less consistently reproducible issue that I've encountered with a higher frequency: If I create a shell script, for example, xx.sh, and write some code in it, then right-click in IDEA to rename it by removing the .sh extension, and then restart IDEA or continue editing for a while, the editor tab for that file suddenly closes automatically and cannot be reopened."

**Comment by jansorg** [comment]
Please post bugs as soon as you find them. I like the software to working as expected :) 

I've found the cause for this. Files without extension need file type detection. I was only using first string content of the file, but the platform isn't passing if incomplete Unicode was found (which is the platform's fault, too).
I'll fix this annoying bug for the next update.

I'll look into the other problem, too.

**Comment by mylovesaber** [comment]
The code above include the bug report that I haven't finished yet. There is no need to translate them. Full report is here:

https://github.com/BashSupport-Pro/bashsupport-pro/issues/183#issue-2577386888

**Comment by jansorg** [comment]
Version 4.3.2 includes the fix and is available now. The other problems you reported is verify likely caused by the same bug.
Please let me know if one of the problems is still showing up with 4.3.2.
Thank you!
