### ISSUE TITLE
Add support for disabling individual ShellCheck rules

### ISSUE THREAD

**Issue by tukusejssirs** [BashSupport-Pro/bashsupport-pro#185]
The following still shows the warning `Double quote to prevent globbing and word splitting`.

```bash
a='one two three'

# shellcheck disable=SC2046
echo $a
```

There are times when some ShellCheck rules must be broken in which case I want to disable then on the following line.

This works when your plugin is not installed.

Thank your for your awesome plugin! :pray:

**Comment by tukusejssirs** [comment]
Actually, it works as expected. It was a typo. Sorry for the noise. :pray:

**Comment by jansorg** [comment]
Thanks for the update.
In general, each warning has an options submenu to automatically insert the suppression comment directive.

https://www.bashsupport.com/manual/editor/shellcheck/#shellcheck-directives
