### ISSUE TITLE
Incompatible with IntelliJ IDEA 2020.2 EAP / Build #IU-202.4357.23

### ISSUE THREAD

**Issue by doublefx** [BashSupport-Pro/bashsupport-pro#22]
Incompatible with IntelliJ IDEA 2020.2 EAP / Build #IU-202.4357.23

![image](https://user-images.githubusercontent.com/1222171/83324010-32b99180-a25a-11ea-998c-8563d45fa571.png)

**Comment by jansorg** [comment]
Thanks for the report! The update will be released very soon - I’m currently waiting for 2020.1.2 to release a major update of BashSupport Pro, including support for 2020.2.

**Comment by jansorg** [comment]
I released the current version for 2020.2 EAP. This is not yet the big update, it will be out soon.
https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/update/87568
