### ISSUE TITLE
spellcheck source=./path/file.sh does not work

### ISSUE THREAD

**Issue by tcf909** [BashSupport-Pro/bashsupport-pro#27]
Example main.sh
```
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null 2>&1 && pwd )"
INCLUDE_DIR="${SCRIPT_DIR}/inc"
# shellcheck source=./inc/LOCK.inc.sh
source "${INCLUDE_DIR}/LOCK.inc.sh"

LOCK_VAR="test" #<<<SYNTAX WARNING ABOUT UNUSED VARIABLE EVEN THOUGH LOCK.inc.sh uses it

LOCK_FUNC
```

I get a warning about relative source includes. The editor also doesn't understand that LOCK_VAR is actually used in LOCK.inc.sh (in addition to not being able to goto file).

**Comment by jansorg** [comment]
This setup is supported, but a few things might prevent this.

- Could you post the version of BashSupport Pro you're using? The current version 1.3.x is supporting variables with shellcheck
- Please make sure you're using BashSupport Pro with the JetBrains Shell plugin ("Shell" has to be enabled in Settings>Plugins>Installed)
- This won't work in scratch files and folders, which are marked as "excluded"

To verify that it's working, these features should work:
- Go to declaration on the filename in `# shellcheck source=./LOCK.inc.sh`
- rename, go to declaration, etc. on "LOCK_VAR" in main.sh

- The warning `Variable seems unused` is from Shellcheck [bug with JetBrains](https://youtrack.jetbrains.com/issue/IDEA-219176). A workaround is to add `# shellcheck disable=SC2034` before (via quickfix) or to disable the shellcheck check (via quickfix `Disable Inspection `LOCK_VAR appears unused``)

**Comment by tcf909** [comment]
1.2.6.193 is the version the marketplace says is available.

We still run 2019.3.5 Intellij (2020 has too many showstoppers for us unfortunately)

Anyway to update to 1.3.x?

**Comment by jansorg** [comment]
I'm sorry, but a backport to BashSupport Pro for 2019.3 isn't possible due to technical limitations.

**Comment by tcf909** [comment]
Ok thanks.

**Comment by jansorg** [comment]
Hi @tcf909, because BashSupport Pro is now a standalone plugin, a backport of the latest release to 2019.3 was possible. I just released the latest version, which is now also compatible with 2019.3.
