### ISSUE TITLE
Markdown code blocks with language bash are not highlighted

### ISSUE THREAD

**Issue by stevencrader** [BashSupport-Pro/bashsupport-pro#31]
After upgrading from Bash Support (non-pro) version 1.7.18.201 to Bash Support 
Pro version 1.4.10.201 in PyCharm 2020.1.3, markdown code blocks with the language bash are not highlighted.

Additionally, I found that after typing <code>```</code>, "bash" isn't even shown as a language in the drop down. I'm not sure where those languages come from but it would be nice if "bash" was still supported.

I found that if I use the language "bashpro shell script" the code block is correctly highlighted but this won't work when the markdown files are viewed in GitLab/GitHub.

Example - used to be highlighted but now isn't

<pre><code>```bash
git status
```</code></pre>

Example - is highlighted but will not be in GitLab/GitHub

<pre><code>```bashpro shell script
git status
```</code></pre>

I also tried it using Bash Support Pro version 1.4.10.202 in PyCharm 2020.2 EAP 4 and see the same.

**Comment by jansorg** [comment]
Thanks for the report. You‘re right, this is a missing piece. I‘ll fix that for the next update. 
Are you using the JetBrains markdown plugin (i.e. the builtin support) or a 3rd-party plugin?

**Comment by jansorg** [comment]
I've fixed this for the next update, which will be out later this week or early next week.

**Comment by stevencrader** [comment]
Thank you. I am using the builtin Jetbrain's markdown plugin.

**Comment by jansorg** [comment]
Version 1.4.11, which fixes this issue, has been released. Please reopen if this isn't working as it should.
