### ISSUE TITLE
Using redirection before a command breaks highlighting, code completion etc...

### ISSUE THREAD

**Issue by xbb** [BashSupport-Pro/bashsupport-pro#35]
Example:

![image](https://user-images.githubusercontent.com/239074/89504640-a337de00-d7c8-11ea-9fb9-27f7ca17ea34.png)

**Comment by jansorg** [comment]
Thanks for the report, I'll take a look and fix it.

**Comment by xbb** [comment]
Thanks! Also I'm not sure if it is related but I have a problem with highlighting inside brackets:

![image](https://user-images.githubusercontent.com/239074/89520679-860e0a00-d7de-11ea-96b8-f7d3677bed58.png)

**Comment by jansorg** [comment]
Thanks! I've fixed both issues for the next update, which should be out next week.

**Comment by jansorg** [comment]
Version 1.4.13 has been released and should fix the problems you reported. Please re-open if this is not the case.
https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/versions/stable/94332
