### ISSUE TITLE
Illegal char <:> at line

### ISSUE THREAD

**Issue by evotodi** [BashSupport-Pro/bashsupport-pro#36]
Can not edit legacy BashSupport run commands that contain a : in the script argument.

**Comment by jansorg** [comment]
@evotodi Thanks for the report! Could you post a screenshot of the run configuration window when you edit it, if possible? That should help to track this down.
Could you also post the system info at `Help>About>ctrl+c/cmd+c`, please?

**Comment by evotodi** [comment]
PhpStorm 2020.2
Build #PS-202.6397.115, built on July 29, 2020
Licensed to Justin Davis
Subscription is active until July 2, 2021
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1972M
Cores: 24
Registry: projectView.hide.dot.idea=false, run.processes.with.pty=TRUE
Non-Bundled Plugins: CMD Support, Scratch, com.intellij.ideolog, com.github.jk1.ytplugin, net.sjrx.intellij.plugins.systemdunitfiles, mobi.hsz.idea.gitignore, com.perl5, pro.bashsupport, com.intellij.plugins.html.instantEditing, com.jetbrains.plugins.jade, com.github.masahirosuzuka.PhoneGapIntelliJPlugin, de.espend.idea.php.phpunit, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, ru.adelf.idea.dotenv
![Annotation 2020-08-06 092320](https://user-images.githubusercontent.com/1625853/89536939-9619ef80-d7c6-11ea-8b04-f8e06748d5c6.png)

**Comment by jansorg** [comment]
Well, this is weird. Is the right part of the window really empty? 
There should've been the settings ui for the run configuration.

**Comment by evotodi** [comment]
Yes. And throws this error.
![Annotation 2020-08-06 094531](https://user-images.githubusercontent.com/1625853/89539312-99fb4100-d7c9-11ea-981e-ab6197c05478.png)

**Comment by jansorg** [comment]
I've fixed this for the next update, which should be out next week. The configuration page will appear as it normally does.

The error message is saying that the script file path contains `server:stop` and that the colon `:` isn't a valid character of windows paths. I assume that this was supposed to go into the script parameters input. With the update you'll be able to edit and fix the settings.

**Comment by jansorg** [comment]
Version 1.4.13 has been released and should fix the problems you reported. Please re-open if this is not the case. Thank you for your patience to track this down!
https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/versions/stable/94332

**Comment by evotodi** [comment]
Works perfectly now. Thank you. See https://github.com/BashSupport-Pro/bashsupport-pro/issues/37#issuecomment-672843371
