### ISSUE TITLE
Structure window can't display function names defined in shells

### ISSUE THREAD

**Issue by binbjz** [BashSupport-Pro/bashsupport-pro#38]
I have defined multiple functions in my shell. Why structure window can't display function names defined in shells？The bundle shell can display normally. Bash Support used to be supported, but now function names cannot be displayed. Please support the function.

<img width="248" alt="Screen Shot 2020-08-10 at 14 56 41" src="https://user-images.githubusercontent.com/8213913/89758467-73ffd480-db1a-11ea-9d75-8a9569320278.png">

**Comment by jansorg** [comment]
@binbjz Thanks for the report. This is supported, at least I couldn't find a file where it's broken.

Could you verify that the plugin BashSupport Pro is enabled at Settings>Plugins>Installed?

The legacy BashSupport plugin [is not supported for 2020.2 and later](https://plugins.jetbrains.com/plugin/4230-bashsupport).  If you only had the BashSupport plugin enabled and updated to 2020.2, then this might explain the missing structure view.

If BashSupport Pro is enabled, could you post the script, which isn't properly displayed in structure view?

**Comment by binbjz** [comment]
Ok, I will try it.

**Comment by binbjz** [comment]
I uninstall "Bash Support" and enable "Shell Script", function name will be displayed in Structure windows.
I disabled "Shell Script" and then reinstall "Bash Support", function name disappears.
For Pycharm, idea and clion, they all have the same problem, so I am confused.

**Comment by binbjz** [comment]
Thanks, BashSupport Pro works well.

**Comment by jansorg** [comment]
Thanks for confirming!
