### ISSUE TITLE
debugger features are not available for me

### ISSUE THREAD

**Issue by zero2cx** [BashSupport-Pro/bashsupport-pro#42]
I am enjoying your extension and really appreciate the active development in progress. 
However, at this time I've seen no evidence that BashSupport Pro debugging is available for me. 
Other BashSupport Pro functionality seems to be working fine for me. 
I've just finished my 30-day Pro trial, during which I never did explore the debugger integration. 
Now that I've purchased my license, I thought I'd try out the debugger but I cannot do so, so far.
- The Debug 'script name' toolbar button is inactive/grayed. 
- The Debug 'script name' context menu item is missing.  
- The Debug tool window is not present anywhere. 

I do have one auxiliary Python script within my current bash project, and THAT single file is allowing me to execute the Python debugger. I have tried uninstalling my operating system's bashdb package, but there appears to be no difference in BashSupport Pro's debugger functionality, with or without the presence of  my system's bashdb executable. Both my IDE and all extensions are latest versions. 

- PyCharm 2020.2 (Professional Edition)
Build #PY-202.6397.98, built on July 27, 2020
Subscription is active until November 2, 2021
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.1-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: IdeaVIM, Key Promoter X, net.seesharpsoft.intellij.plugins.csv, zielu.gittoolbox, aws.toolkit, com.jetbrains.edu, pro.bashsupport
Current Desktop: Deepin

- $ which bash
/usr/bin/bash
- $ bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
- $ which bashdb
/usr/bin/bashdb
- $ bashdb --version
bashdb, release 5.0-1.1.2

**Comment by zero2cx** [comment]
I may have been doing something wrong. The debugger integration is working fine now.

**Comment by jansorg** [comment]
Glad that it‘s working now for you. 
Is it working now for every file or is there still a file where it#s not? e.g. a file without extension
Do you remember what you did to make this work?

bashdb is bundled with the plugin, so your system‘s version is not used.

**Comment by zero2cx** [comment]
Thanks for the quick response. 
I was trying to set breakpoints, etc. in bats tests and I now realize that's not actually a thing. My desription above was faulty, as the debugger was always functional for my single bash script in the project. It just wasn't working for my 20+ bats test scripts. So this all was simply an oversight on my part. 

Q) Is there any way to set a breakpoint within my bash script, and then have my bats test(s) honor that breakpoint, and enter the debugger whenever the test is launched? That's the behavior I might wish to see. But it may be not doable at this point, due to the way bats-core works.

**Comment by jansorg** [comment]
Thanks. Debugging bats tests isn‘t possible. It would definitely be useful, though. 
I‘ll investigate for one of the next versions, but I fear that this won‘t work well. bats files are not fully compatible with bash and are therefore transformed by the bats testrunner before they‘re executed.

**Comment by zero2cx** [comment]
Sounds good. Thanks a lot.
