### ISSUE TITLE
Built in Makefile support in CLion relies on Shell plugin, which is incompatible with BashSupport Pro

### ISSUE THREAD

**Issue by vlebourl** [BashSupport-Pro/bashsupport-pro#46]
As said in title, can't use this extension in a Makefile project.

**Comment by jansorg** [comment]
@vlebourl Thanks for reporting. I checked the CLion Makefile support a few days ago. I'm not sure why the Makefile plugin depends on the Shell Script plugin, I'll have to try to contact JetBrains to find out about it. It's not possible for me to fix this on my end.
It's not used for highlighting, that's what the "Makefile Support" plugin does (https://blog.jetbrains.com/clion/2020/06/makefile-projects-in-clion/), so I'm unsure how the Shell plugin is used.

Here's what you could try as a workaround:
- Although BashSupport Pro asks you to disable Shell, it should still be working alongside. The notification at startup will be hidden forever after the third time you clicked "Hide" on the message. See below for known issues. 
- Disadvantes: Although BashSupport Pro integrates with the "Makefile Support" highlighting, this is overridden by the Shell Script's integration. I could try to fix that with an update, but can't promise that this is possible.
- Advantages: Shell script files will be opened with BashSupport Pro.

**Comment by vlebourl** [comment]
Thanks for the quick answer! I will apply that workaround. Feel free to close this issue. 
Cheers

**Comment by jansorg** [comment]
Let me know if it doesn't work as needed.
I'll leave this open, because the integration isn't ideal and definitely confusing to users.
I've opened https://youtrack.jetbrains.com/issue/CPP-22069 and hope that JetBrains will provide a few details.

**Comment by jansorg** [comment]
JetBrains said, that the Shell plugin is currently used to analyze the Makefile, but that they may drop the dependency in the future. I've just released 1.5.8, which doesn't warn on CLion anymore. Let's see if that was a good change ;)
