### ISSUE TITLE
EAP 2020.3 compatibility

### ISSUE THREAD

**Issue by stevencrader** [BashSupport-Pro/bashsupport-pro#49]
EAP 2020.3 has been released.

https://blog.jetbrains.com/pycharm/2020/09/pycharm-2020-3-eap-starts-now/

**Comment by jansorg** [comment]
@stevencrader Thanks!
I've already made the changes and I'm planning to release a new version later this week, which includes support for 2020.3.

**Comment by jansorg** [comment]
@stevencrader There's an eap version for 2020.3 at https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/versions/eap . The stable version has been delayed and should be out next week, hopefully

**Comment by BorzdeG** [comment]
To add as a custom repository as a link: https://plugins.jetbrains.com/plugins/eap/13841

**Comment by ddnexus** [comment]
@jansorg I tried to install the plugin with RubyMine EAP 2020.3 (latest available EAP), but it looks like there is a version requirement mismatch:

![Screenshot from 2020-10-01 19-53-13](https://user-images.githubusercontent.com/100721/94811823-143def80-0420-11eb-8444-442ad2a08d34.png)

**Comment by jansorg** [comment]
@ddnexus Thanks for reporting! The RubyMine EAP build seems to be a slightly version than the IntelliJ build, which has to be used for development. I'll ship a compatible version soon.
