### ISSUE TITLE
Intellisense incorrectly suggests $BATS_TEST_TMPDIR

### ISSUE THREAD

**Issue by zero2cx** [BashSupport-Pro/bashsupport-pro#50]
Hello. This is unintended behavior for the (BashSupport Pro 1.5) plugin, I think.
I intend to use Intellisense (PyCharm 2020.2) to see `$BATS_TMPDIR` suggested for insertion into the code.
So I type `$BATS_` and I see the dropdown / pop-up with some completion suggestions.
There is `$BATS_TEST_TMPDIR` listed with the other suggestions.
That is the incorrect behavior to which I refer, while the correct `$BATS_TMPDIR` is not included in the list.

**Comment by jansorg** [comment]
Thanks for reporting! 
1.5 added completions of the built-in bats-core variables, previous versions did not suggest these variables.

You're right, that suggesting `$BATS_TEST_TMPDIR` is invalid. It should've been `$BATS_TMPDIR`.

I'll fix that for the next minor update.

**Comment by jansorg** [comment]
This has been fixed with the latest update 1.5.9.

**Comment by zero2cx** [comment]
Your extension's growing feature set and your client support are both excellent. Thank you for the update!
