### ISSUE TITLE
Plugin breaks "Code Completion" feature of IDE

### ISSUE THREAD

**Issue by MGerasimchuk** [BashSupport-Pro/bashsupport-pro#51]
Hello,
I use Bash Support Pro (1.5.8.202) plugin in my PHPStorm IDE(PhpStorm 2020.2.2 #PS-202.7319.77).
And if I have enabled the Bash Support Pro plugin in my project, my code completion feature doesn't work after type "->" symbol, and only work after type at least one symbol.
On another hand, if I disable the Bash Support Pro plugin, the code completion feature of IDE again works correctly.

Also, you can see this behavior on the screenshots:

| With disabled Bash Support Plugin | With enabled Bash Support Plugin |
|---|---|
| ![image](https://user-images.githubusercontent.com/13135129/95084424-1073db00-0748-11eb-9bc7-b46421f57ad2.png) | *it's a incorrect behavior ![image](https://user-images.githubusercontent.com/13135129/95084306-e7534a80-0747-11eb-92c5-6906cd3ede06.png) |
| ![image](https://user-images.githubusercontent.com/13135129/95084440-179ae900-0748-11eb-99df-4da9d255fbc0.png) | ![image](https://user-images.githubusercontent.com/13135129/95084347-f3d7a300-0747-11eb-9849-432439434f53.png) |

**Comment by jansorg** [comment]
@MGerasimchuk Thanks for reporting! This definitely shouldn't be happening.

I was able to reproduct this with the automatic code completion, i.e. the popup with `myMethod()` isn't shown automatically when typing `->`. Is that also what you're observing?

Is `myMethod()` shown properly after `->` when you manually invoke it (with Ctrl+Space)? 

There's nothing in the plugin for .php files and/or code completion for files, which are not shell scripts. 
I'll fix this and release an update very soon.

**Comment by jansorg** [comment]
@MGerasimchuk Fixed for the next update, which will most likely be out later today.
Thanks for the detailed report, that's really appreciated.

BashSupport Pro triggers autocompletion, when `$` or `${` is typed in shell script files. A bug caused this to break some of auto completion popups of some other languages.

**Comment by MGerasimchuk** [comment]
@jansorg thank you for the fast reaction on this problem.

**Comment by jansorg** [comment]
The update with the fix is available now.
