### ISSUE TITLE
Support GoLang 2020.1 Nightly

### ISSUE THREAD

**Issue by BorzdeG** [BashSupport-Pro/bashsupport-pro#52]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/2332528/97099760-b064ba80-169d-11eb-914f-1995c1463bf4.png">
<img width="322" alt="image" src="https://user-images.githubusercontent.com/2332528/97099769-beb2d680-169d-11eb-9e96-c06ebc03561b.png">

EAP plugin repository is connected: https://plugins.jetbrains.com/plugins/eap/13841

**Comment by jansorg** [comment]
Thanks, I never noticed that GoLand has nightly builds. I‘ll see what I can do.

**Comment by BorzdeG** [comment]
the GoLand team reported that version 2021.1 is a false start and an actual nightly build is 2020.3

https://golang-ru.slack.com/archives/C02C57ECP/p1603608887106100

**Comment by jansorg** [comment]
Thanks for the follow-up (can't read the russian slack channel, though). The current version is available for 2020.3 eap. I don't expect that 2021.1 eap will be available before next year, I'll provide an eap as soon as it's there.
