### ISSUE TITLE
what if I don't need shebang?

### ISSUE THREAD

**Issue by progreccor** [BashSupport-Pro/bashsupport-pro#54]
I an writing code for mc.menu (shell code for menu for midnight commander).
And this file don't need any shebang line. 
How could I disable this warning?
![2020-11-08_10-58-35](https://user-images.githubusercontent.com/3103677/98460020-6c030f80-21b1-11eb-9cab-32b75cf4e654.png)

**Comment by jansorg** [comment]
@progreccor You can add `# shellcheck shell=bash` (for Bash) or `# shellcheck shell=sh` (POSIX) as the first line of the file to make this message disappear.
Are you on the latest version? 1.5.8 added a quickfix to help you insert this.

**Comment by progreccor** [comment]
The problem is that I can't set this line as a first line...
shell_patterns=0 MUST be the first line of the file for mc.menu ....
So I don't know what should I do....

**Comment by progreccor** [comment]
![Скриншот 09-11-2020 124530](https://user-images.githubusercontent.com/3103677/98525417-7a245f00-2289-11eb-9b2d-a7157c6afbb8.png)

**Comment by jansorg** [comment]
Hm, that's unfortunate. File extension, shebang and `shellcheck shell=` control the shell dialect. None of this is possible in your case.

I see two ways to fix this:

You could disable that warning by excluding the ShellCheck rule for all files:
1. Open `Settings > Languages & Frameworks > BashSupport Pro`
2. Add `-e SC2148` to the text field `ShellCheck arguments`
This disables the warnings, but will only support POSIX features.


Hacky, only on macOS or Linux, but with Bash syntax support: create a sym link `mc-menu.bash` to `mc.menu` and edit `mc-menu.bash` instead. The file extension will tell ShellCheck and BashSupport Pro to support Bash syntax.

**Comment by progreccor** [comment]
Yes, totally disable this feature help me...

Thank you for support.

Also - appreciate your effort and use Pro version that bought about two months ago.
I know much more about bash with help of your plugin. So another thank you!
