### ISSUE TITLE
Plugin has became incompatible with IDEA community

### ISSUE THREAD

**Issue by grumpyf0x48** [BashSupport-Pro/bashsupport-pro#57]
I'm running IntelliJ IDEA Community 2020.2.4 (202.8194.7) and i now have the following message:

18:03	Plugin Error: Plugin "BashSupport Pro" is incompatible (since build 203.5981.0 > IC-202.8194.7).

which leads to BashSupport-Pro being disabled.

Is there a new version planned to remain compatible with IDEA Community ?

**Comment by jansorg** [comment]
@grumpyf0x48 
BashSupport Pro is still available for 2020.2, including IntelliJ Community. 
But there's a different version for each major version of the IDEs.
For 2020.2 it's 1.5.12.202: https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/versions/stable/103672
For 2020.3 it's 1.5.12.203: https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/versions/stable/103673

Can you tell how you installed this incompatible version? Let me know if you think that the install instructions aren't clear enough.

To fix this, I'd first try "Help>Check  for Updates". If that's not helping, then I'd uninstall it at Settings>Plugins>Installed, restart and install again via Settings>Plugins>Marketplace>Enter "BashSupport" and install.
Does that help?

I verified that `#IC-202.8194.7` installed BashSupport Pro.

**Comment by grumpyf0x48** [comment]
Indeed, the version i had was 1.5.12.203 which is not compatible with my IDEA version as you said.

I have installed BashSupport-Pro in last september, i don't remember the IDEA version at this time. I guess this version has been (wrongly) upgraded from 1.5.12.202 with Intellij & plugins upgrades.

"Help>Check for Updates" didn't worked so i uninstalled the 1.5.12.203 and installed the plugin again. The proposed version was 1.5.12.202 so it is now working properly !

Thanks for the quick reply.

**Comment by jansorg** [comment]
Thanks for confirming that it's working now. IntelliJ shouldn't install incompatible versions, but there might a bug in IntelliJ. I'll keep an eye on it.
