### ISSUE TITLE
cannot parse "test -v array[key]"

### ISSUE THREAD

**Issue by thorstenkampe** [BashSupport-Pro/bashsupport-pro#58]
BashSupport cannot parse  `test -v array[key]` (test if array has key or index with value) available with bash 4.3.

This results in completion being unavailable in the whole script.

![image](https://user-images.githubusercontent.com/475462/103238358-c8c9ad80-494a-11eb-8bda-5efd0883cca3.png)

**Comment by jansorg** [comment]
Thanks for reporting, I'll fix that. I'm currently working on parser improvements, so this should make it into 2.0

**Comment by jansorg** [comment]
This has been fixed in the meantime for 2.0, the latest beta is at https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/next-version
