### ISSUE TITLE
Upgraded to Big Sur and latest PHPstorm - Code Folding Broke

### ISSUE THREAD

**Issue by thewzrd** [BashSupport-Pro/bashsupport-pro#60]
CMD +/-

Works to fold/unfold one level of code

SHIFT CMD +/-

To fold/unfold ALL are no longer working...

I am needing to use the top menu bar to navigate through... it's painful

<img width="707" alt="Screenshot 2021-01-14 at 16 58 25" src="https://user-images.githubusercontent.com/3505490/104567583-e8224380-5689-11eb-9854-d62bdc410325.png">

**Comment by aosmichenko** [comment]
@thewzrd why it was closed? did you fixed the issue? I have the same ;(

**Comment by jansorg** [comment]
This issue has a few more notes: https://github.com/BashSupport-Pro/bashsupport-pro/issues/61
