### ISSUE TITLE
PHPStorm update - Broken Code Folding

### ISSUE THREAD

**Issue by JeffCleverley** [BashSupport-Pro/bashsupport-pro#61]
CMD +/-

Works to fold/unfold one level of code

SHIFT CMD +/-

To fold/unfold ALL are no longer working...

I am needing to use the top menu bar to navigate through... it's painful

<img width="707" alt="Screenshot 2021-01-14 at 16 58 25" src="https://user-images.githubusercontent.com/25419360/104567819-37687400-568a-11eb-8143-7d583587a6dc.png">

I updated to big sur and then updated phpstorm

**Comment by jansorg** [comment]
@JeffCleverley Thanks for reporting! This seems a bit like an incompatibility with PHPStorm, because the shortcuts are handled by the IDE. In this case "Expand all" would be broken for all file types.
Later, I'll test on Big Sur and report my findings.

**Comment by JeffCleverley** [comment]
I have some PHP projects somewhere, never thought to check those, ill also disabled bashsupport pro.

**Comment by JeffCleverley** [comment]
Yup, its knackered without plugin installed and on other types. I'll close this out and report there. Apologies.

**Comment by jansorg** [comment]
Thanks for the follow-up!

**Comment by JeffCleverley** [comment]
Just so you know:
https://youtrack.jetbrains.com/issue/IDEA-258389

Seems key bindings are being messed up and using shift + - is resulting in an underscore being interpreted.
