### ISSUE TITLE
Problem with process substitution inside command subsitution

### ISSUE THREAD

**Issue by bryder** [BashSupport-Pro/bashsupport-pro#64]
Firstly thanks for bashsupport-pro !

The parser seems to get confused when you use process substitution inside a command substituion

```bash
#!/bin/bash

# This is fine - no errors detected
diff <( printf "one\ntwo\n" | grep one) <(printf "one\ntwo\none\n" | grep one)

# This is checked incorrectly and you get the error
#  <redirection> or <simple command element> expected, got '<(printf'
avar="$(diff <( printf "one\ntwo\n" | grep one) <(printf "one\ntwo\none\n" | grep one) )"
echo "$avar"

```

**Comment by jansorg** [comment]
@bryder Thanks for reporting!
I've fixed this for the next update. 
Nesting of proceses substitutions wasn't handled very well, the fix will improve this.

1.5.14 was just released and I don't want to pester users with updates, so I'm planning to release it end of next week at the earliest.
But I can upload a preview build here if you want to use this earlier.
In this case let me know which major version you're using (e.g. 2020.3).

**Comment by bryder** [comment]
Hi!

Thanks for the quick reply!

I would like to try the preview build please.

I have another bug which is not process substitution and I'll see if that still occurs with the preview and will make a separate issue for that.

**Comment by bryder** [comment]
Ahh - sorry - I missed the essential information:

I'm running 2020.3 and would like to try out 2021.1 but that's not essential.

**Comment by jansorg** [comment]
@bryder Here's a preview build (version 1.5.14.2) for 2020.3.
You have to download the ZIP and then install via "Settings > Plugins > Install from disk" or just Drag&Drop it onto the IDE's main window.

[bashsupport-pro-1.5.14.2.203.zip](https://github.com/BashSupport-Pro/bashsupport-pro/files/5949847/bashsupport-pro-1.5.14.2.203.zip)

**Comment by bryder** [comment]
That works fine thank you!

Feel free to close this issue (I don't know if I should or if you should after the fix is released to the production versions).

**Comment by jansorg** [comment]
Thanks for confirming! I‘ll close this when the public release is available.

**Comment by jansorg** [comment]
1.5.15 is now avaialable and has the fix for this issue.
