### ISSUE TITLE
/bashdb/init/term-background.sh: line 66: 16#: invalid integer constant (error token is "16#")

### ISSUE THREAD

**Issue by synox** [BashSupport-Pro/bashsupport-pro#66]
When debugging any bash script, it prints the errror: 
> /Users/user/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/bashsupport-pro/bashdb/5.0/share/bashdb/init/term-background.sh: line 66: 16#: invalid integer constant (error token is "16#")

And any variables defined in the Run config are missing. 

Script: 
```
#!/usr/local/bin/bash

echo hi, $APP
```

Full output: 
```
/usr/local/bin/bash "/Users/user/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/bashsupport-pro/bashdb/5.0/bashdb" --quiet --no-highlight --library "/Users/user/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/bashsupport-pro/bashdb/5.0/share/bashdb" --tty_in _DBG_PTY_ --tty _DBG_PTY_ /Users/user/project/test.bash
/Users/user/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/bashsupport-pro/bashdb/5.0/share/bashdb/init/term-background.sh: line 66: 16#: invalid integer constant (error token is "16#")
hi,

Process finished with exit code 0
```

versions: 
IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
BSP: 1.5.14.203 and also with 2.0.0.203-beta4

**Comment by jansorg** [comment]
@synox Thanks! bashdb doesn't seem to be able to find the color settings, I'll fix that for the next update.

- You're on macOS, right?
- Could you post the output of `/usr/local/bin/bash --version`, please?
- bashdb calls `osascript -e 'tell application "Terminal" to get the background color of the current settings of the selected tab of front window'`. Could you post the output of that, too, please?

**Comment by synox** [comment]
Yes, macos `10.15.7 (19H524)`
```
❯ /usr/local/bin/bash --version
GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin19.6.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

❯ osascript -e 'tell application "Terminal" to get the background color of the current settings of the selected tab of front window'
65535, 65533, 65534
```

**Comment by jansorg** [comment]
@synox I've fixed `16#: invalid integer constant`, which was a problem with bashdb. This wasn't discovered during my own testing, because it only happens when `pygmentize` is available in `$PATH`.

I've also fixed the missing environment variables.
Both fixes will be released with the next update, scheduled for later this week.

**Comment by jansorg** [comment]
Version 1.5.15 with a fix for both issues is now available.

**Comment by synox** [comment]
Thanks, it works!
