### ISSUE TITLE
Problem parsing

### ISSUE THREAD

**Issue by OscarAkaElvis** [BashSupport-Pro/bashsupport-pro#67]
Hi, I'm one of the developers of [airgeddon](https://github.com/v1s1t0r1sh3r3/airgeddon) script. I'm using bashsupport pro and I saw that from some point, a bad parsing is done and everything is messed up from that point.

Here is a screenshot of the code. From the highlighted line, everything is messed up:

![image](https://user-images.githubusercontent.com/5803348/110299000-7e714680-7ff5-11eb-81fe-537ecec2d749.png)

They are a backtick and a single quote chars escaped. Can this be checked? thanks!

**Comment by jansorg** [comment]
Thanks! Fixed for the next update of 1.5, which should be out later this week.

**Comment by OscarAkaElvis** [comment]
Awesome. You can close this I think.

**Comment by jansorg** [comment]
Version 1.5.16 with a fix for this bug has been released. Please let me know in case this isn't fully fixed for you.
