### ISSUE TITLE
2.0.0.211-beta6-eap thinks a variable set by readarray is unset

### ISSUE THREAD

**Issue by bryder** [BashSupport-Pro/bashsupport-pro#70]
For 2.0.0.211-beta6-eap

Should I be raising issues about the beta unresolved variable functionality?

I'll stop if not since I know it's in beta.

```bash
readarray var <<<"stuff and things"
printf ${var[0]}
```

**Comment by jansorg** [comment]
Yes, please post issues you discover.

**Comment by jansorg** [comment]
Thanks, fixed for the next eap update.
