### ISSUE TITLE
v2: syntax highlighting broken after early exit

### ISSUE THREAD

**Issue by ciarancourtney** [BashSupport-Pro/bashsupport-pro#74]
For example:

```bash
echo foo
[ -n "$BAZ" ] && exit 0
echo bar
```

Appears as:
![image](https://user-images.githubusercontent.com/6096029/121341332-77b9de80-c918-11eb-8163-ed72187380d8.png)

**Comment by jansorg** [comment]
Thanks, I'll fix it for the next beta.

**Comment by jansorg** [comment]
Fixes for the next beta

**Comment by jansorg** [comment]
2.0 beta11 with the fix is now available in the EAP channel.
