### ISSUE TITLE
When using the add function comment in google style mode it thinks local variables are global

### ISSUE THREAD

**Issue by bryder** [BashSupport-Pro/bashsupport-pro#75]
I'm using 

- BashSupport Pro 2.0.0.211-beta14-eap
- IntelliJ IDEA 2021.1.2 (Ultimate Edition)
- Build #IU-211.7442.40, built on June 1, 2021

With this script
```bash
#!/bin/bash
some_function(){
  local this_is_local
  this_is_local="not global"
}
```

It inserts this comment

```bash
#######################################
# description
# Globals:
#   this_is_local
# Arguments:
#  None
#######################################
```

When I hover over the variable it knows it's local so that part is working properly.

**Comment by jansorg** [comment]
Thanks! I've fixed this for the next preview of 2.0.
