### ISSUE TITLE
It doesn't realise a nested function can access parent local variables

### ISSUE THREAD

**Issue by bryder** [BashSupport-Pro/bashsupport-pro#77]
I believe bashsupport-pro is doing this inspection because it seems much smarter than the shellcheck implementation. 

The inner function has access to all of the parent local variables. 

I get the error: var1 is referenced but not assigned

Here's a bats test to demo it.

```bats
outer(){
  local var1="var1_from_outer"
  local var2="var2_from_outer"
  inner(){
    local var2="var2_from_inner"
    echo "inner ${var1} ${var2}"
  }
  inner
  echo "outer ${var1} ${var2}"
}
assert_equal(){
  local expected="$1"
  local actual="$2"
  local caller="${BASH_LINENO[0]}"
  local msg="expected: ${expected} did not match actual: ${actual} assert called from line: ${caller}"
  [[ "${actual}" == "${expected}" ]] || { echo "${msg}" ; false;  }
  true
}
@test 'inheriting_local_in_nested_functions' {

  readarray -t lines <<<"$(outer)"
  for line in "${lines[@]}" ; do
    read funcname actual_var1 actual_var2 <<<"${line}"

    case "${funcname}" in
    "inner")
       assert_equal "${actual_var1}" "var1_from_outer"
       assert_equal "${actual_var2}" "var2_from_inner"
    ;;
    "outer")
       assert_equal "${actual_var1}" "var1_from_outer"
       assert_equal "${actual_var2}" "var2_from_outer"
    ;;
    "*")
      assert "funcname was ${funcname} not inner or outer" ;;
    esac
  done

}
```

**Comment by jansorg** [comment]
@bryder Thanks for reporting, that's highly appreciated!
BashSupport Pro has to replace ShellCheck's reference checks, because it supports more features: project variables, user define libraries and also definitions in files sourcing the current file.

I've fixed this for the next beta of 2.0, but there may be a few more edge-cases.

**Comment by jansorg** [comment]
@bryder The beta with the fix has been released yesterday. Let me know if you discover anything else which seems odd :)

**Comment by bryder** [comment]
All looking good so far thanks!
