### ISSUE TITLE
Variable used indirectly is incorrectly flagged with "x appears unused"

### ISSUE THREAD

**Issue by sourcedelica** [BashSupport-Pro/bashsupport-pro#80]
A variable used indirectly is triggers the Unused global variable inspection.  In this example, `x` is flagged:
```
x="MY${stack}"
echo "${!x}"
```
Version 2.0.3.2111

**Comment by jansorg** [comment]
Thanks!
The implementation of indirect use follows https://github.com/koalaman/shellcheck/wiki/SC2034#indirection, but it's possible to fix this for this particular case. 

It won't help with `${!x*}` and the related cases, but I'll add a fix for `${!x}`.

**Comment by jansorg** [comment]
Fixed for the next update

**Comment by sourcedelica** [comment]
Thanks!

**Comment by jansorg** [comment]
Version 2.0.4 with the fix is now available.

**Comment by sourcedelica** [comment]
It works - thanks!
