### ISSUE TITLE
Shell Script plugin is required for full Dockerfile support

### ISSUE THREAD

**Issue by speller** [BashSupport-Pro/bashsupport-pro#81]
After turning off the builtin shell plugin in favor of BashSupport Pro, I see the following message on Dockerfiles:

![image](https://user-images.githubusercontent.com/1829515/127797574-96f7b56d-43d3-40dd-b624-e511484b31ef.png)

How to fix that?

**Comment by jansorg** [comment]
As soon as 2021.2.1 is out, BashSupport Pro is able to fix this.
Unless you really need shell support in Dockerifles, I'd suggest to ignore the warning until the update is available.

A few more details:
2021.2 now supports language injection into Docker files. Unfortunately it assumes that Shell is always providing this, but it's possible to override this in BashSupport Pro.
2021.2 has a bug which currently prevents working language injection (https://youtrack.jetbrains.com/issue/IDEA-274167).
As soon as this is fixed (hopefully 2021.2.1) I'll provide an update of BashSuppot Pro which provides language injection into Dockerfiles and without the warning above.

**Comment by jansorg** [comment]
Version 2.0.5 with support for Docker language injection is now available. 
You'll need a 2021.2.1 eap build, 212.5080.0 or later. The final 2021.2.1 release should be available soon.
https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/versions/stable/133970
