### ISSUE TITLE
Code Style not reflected in code 

### ISSUE THREAD

**Issue by cduhn2075** [BashSupport-Pro/bashsupport-pro#83]
Code style formatting not observed in code or after code reformatting
* tab size 
* indent

**Comment by jansorg** [comment]
Thanks! Yes, there seems to be a problem with the handling of indentation. I'll fix that for the next update.

**Comment by jansorg** [comment]
Fixed for the next update. The settings were not stored correctly. I'll close this when the update is available.

**Comment by jansorg** [comment]
Version 2.0.4 with the fix is now available.
