### ISSUE TITLE
bats-core fails to run individual test case when variable in test name

### ISSUE THREAD

**Issue by timja** [BashSupport-Pro/bashsupport-pro#84]
If I try run:
https://github.com/jenkinsci/docker-agent/blob/6ac292e7c5c8c5132f9c08ba29ef86f5f16f26af/tests/tests.bats#L12

I get no tests found

Workaround:

Change line to be:
```
@test "[] checking image metadata" {
```

We use that syntax because we run the tests multiple times with different docker image flavours and it appears in the output with the agent that was being run.

I'm happy enough removing the variables when I need to, but it would be nice to fix

**Comment by jansorg** [comment]
Thanks for reporting! I've fixed this for the next update (2.1.0).

**Comment by timja** [comment]
Thank you!
