### ISSUE TITLE
How to default to JetBrains Shell Script plugin run configuration

### ISSUE THREAD

**Issue by wronnyhuang** [BashSupport-Pro/bashsupport-pro#88]
Hello,

I like BashSupportPro for code syntax highlighting, but I sometimes get issues I run with the BashSupportPro run configuration. I would like to use the JetBrains shell script run configuration by default, but whenever I go to [Run] -> [Run...] from the context of my shell script in the editor, the only option is the BashSupportPro run config.

![image](https://user-images.githubusercontent.com/23001184/137173901-2e513b5b-581d-46af-b7ac-945fc37b99be.png)

As a result, I need to manually make a run config for each new shell script I write. Is it possible to use the JetBrains Shell Script run configs by default, or to even disable the BashSupportPro run config?

Some context: https://www.bashsupport.com/manual/run/

**Comment by jansorg** [comment]
@wronnyhuang Thanks for reporting!
Could you explain what kind of issues you're experiencing with the BashSupport Pro run configurations?

There are two possible handlers of the "JetBrains Shell run configuration" type:
1. BashSupport Pro handling the same file format, https://www.bashsupport.com/manual/run/legacy-shell/ . Is this the configuration you're creating?
2. The JetBrains Shell plugin handling the run configuration, https://www.jetbrains.com/help/idea/run-debug-configuration-shell-script.html

Only (1) is possible while the BashSupport Pro plugin is active.
(1) is not created by default, e.g. when creating a new configuration with the context menu. 
If you need (1), then I could provide a setting to create the run configurations compatible with "JetBrains Shell" by default. Would that be helpful for your use case?

**Comment by jansorg** [comment]
This will be implemented with 4.0, the next major version.

**Comment by jansorg** [comment]
This is available with 4.0 now. https://www.bashsupport.com/manual/settings/
