### ISSUE TITLE
A for (( expr1; expr2; expr3)) { list ; } emits an error

### ISSUE THREAD

**Issue by bryder** [BashSupport-Pro/bashsupport-pro#89]
I'm running bashsupport-pro 2.0.3.212 on IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 13, 2021
Bash 4.4

This works in bash
```bash
for (( i=0; i<2; i++ )) { echo $i ; } 
```
as does

```bash
for (( i=0; i<2; i++ )) {
   echo $i 
}
```
Both forms get an error 
```
<list terminator> expected, got '{'
```
 at the left brace in bash support pro 

Interestingly I can't find anything in the bash man page for bash 4.4 to say it's legal. But they do work.

This does work without error
```bash
for (( i=0 ; i < 2 ; i++ )) ; { echo "$i"; }
```

So I guess there's something special about the '{' reserved word in bash.

**Comment by jansorg** [comment]
I've fixed this for 2.1, which will be out next week.
