### ISSUE TITLE
BATS_TEST_TMPDIR and BATS_SUITE_TMPDIR are not supported

### ISSUE THREAD

**Issue by dihuynh** [BashSupport-Pro/bashsupport-pro#94]
BATS_TEST_TMPDIR and BATS_SUITE_TMPDIR are special variables in bats-core. https://bats-core.readthedocs.io/en/stable/writing-tests.html#special-variables. BATS_TMPDIR is not unique per test therefore it is not a sufficient replacement. 

The variables are also not on the autocomplete dialog. ![image](https://github.com/dihuynh/bash-support-pro-issues/blob/main/Screen%20Shot%202021-12-02%20at%2011.17.14%20AM.png)

### Reproduction steps:
Run the following test in IntelliJ
```
@test "test tmpdirs vars are not available" {
  echo "TEST_TMPDIR " $BATS_TEST_TMPDIR >&3
  echo "SUITE_TMPDIR " $BATS_SUITE_TMPDIR >&3
}
```
The output is 
```
TEST_TMPDIR
SUITE_TMPDIR
```

### Versions:
BashSupportPro 2.0.6.212
IntelliJ IDEA 2021.2.3 (Ultimate Version)

**Comment by jansorg** [comment]
@dihuynh Thanks for reporting!
Version 2.0.6 bundles bats-core 1.3. But the two TMPDIR variables above were added with version 1.4 (https://github.com/bats-core/bats-core/releases/tag/v1.4.0).
I'm currently preparing version 2.1, which bundles the current version 1.5 or bats-core. This version of the plugin will also show the two variables in the autocomplete dialog and also quick documentation.
A preview of the complete list of variables is available at https://preview.bashsupport.com/bash/variables/bats-core/

Please let me know if there's anything else wrong with the bats-core support!

**Comment by jansorg** [comment]
There's a release candidate of the new version at https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/eap-bashsupport-pro-2-1, just in case you'd like to try updated bats-core support.

**Comment by dihuynh** [comment]
@jansorg the release candidate works great. Thank you so much!

**Comment by jansorg** [comment]
Thanks! I'm closing this now, the new release is now available for everyone.
