### ISSUE TITLE
Incorrect use of variable scope in read command

### ISSUE THREAD

**Issue by inode64** [BashSupport-Pro/bashsupport-pro#97]
```
Example() {
	local line
	find /etc | while read -r line; do
		echo
	done
}

Example2() {
	local line
	find /etc | while read -r line; do
		echo "$line"
	done
}
```
In the Example function, it incorrectly shows the variable line locally as not used and while it shows that line is for global use
And in Example2 reports that the line variable in the echo as global
the 2 functions should always be local variables

- PhpStorm 2021.3
- BashSupport Pro 2.1.1.213

**Comment by jansorg** [comment]
The difficulty here is that the pipeline `find /etc | while read -r line` creates an implicit subshell.
This subshell restricts the visibility of its variable declarations.

**Comment by jansorg** [comment]
Meanwhile, support for implicit subshells has been added for the upcoming BashSupport Pro 3.0. Preview versions are already available at https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/eap-bashsupport-pro-3-0
